- app/components/AppComponents.scala
- app/controllers/Amigo.scala
- app/controllers/Auth.scala
- app/controllers/AuthActions.scala
- app/data/Bakes.scala
- app/data/BaseImages.scala
- app/data/DynamoFormats.scala
- app/data/Recipes.scala
- app/models/Bake.scala
- app/views/showRecipe.scala.html
- build.sbt
- conf/application.conf
- conf/routes
- project/plugins.sbt
> Add Google auth

- app/components/AppComponents.scala
- app/controllers/Amigo.scala
- app/packer/PackerRunner.scala
> Switch to Akka Streams

- app/components/AppComponents.scala
- app/controllers/Amigo.scala
- app/models/packer/PackerBuilderConfig.scala
- app/packer/PackerBuildConfigGenerator.scala
- app/packer/PackerRunner.scala
- app/prism/Prism.scala
- test/prism/PrismSpec.scala
And tell Packer to share the generated AMI with those accounts
@Reettaphant
Fixes #19
> Use Prism to lookup all Guardian AWS account numbers

- app/models/BakeLog.scala
- app/packer/PackerOutputParser.scala
- test/packer/PackerOutputParserSpec.scala
> Support ANSI-coloured text in Packer logs

- cloudformation.json
These changes have already been applied in PROD
> CloudFormation changes to enable HTTPS on ELB

- roles/node/defaults/main.yml
- roles/node/tasks/main.yml
> Node js role

- app/components/AppComponents.scala
- app/packer/PackerBuildConfigGenerator.scala
- app/packer/PackerConfig.scala
@cb372 Adds the tags like we discussed. Lemme know if you think this implementation makes sense?
> Additional ami tags

- app/views/editBaseImage.scala.html
- app/views/editRecipe.scala.html
- app/views/newBaseImage.scala.html
- app/views/newRecipe.scala.html
Ensure that checkboxes don't jump around the page when editing base images or recipes.
> ensure checkboxes don't jump around

- roles/imagemagick/tasks/main.yml
- roles/imgops-logrotate/tasks/main.yml
- roles/nginx-extras/tasks/main.yml
- roles/pngquant/tasks/main.yml
- Add roles needed for cropper and imgops in grid @kenoir
> Add roles for grid

- roles/kong/README.md
- roles/kong/defaults/main.yml
- roles/kong/files/configure.sh
- roles/kong/files/kong-0.7.0.yml
- roles/kong/files/kong.logrotate
- roles/kong/meta/main.yml
- roles/kong/tasks/main.yml
Created with @LATaylor-guardian and tested on CODE.
> Add a role to install Kong 0.7.0

- roles/exiftool/meta/main.yml
- roles/exiftool/tasks/main.yml
> Adds exiftool role

- roles/kong/defaults/main.yml
https://github.com/Mashape/kong/releases/tag/0.9.1
> Kong 0.9.1 is out

- app/ansible/RoleParser.scala
- app/views/showBake.scala.html
- public/javascripts/amigo.js
- public/javascripts/show-bake.js
- public/stylesheets/main.css
* Put the logs inside a well that fits on the screen
* Tail the log (on by default, can be toggled with a checkbox)
> Prettify the bake page

- public/javascripts/amigo.js
- public/javascripts/show-bake.js
This broke the roles page during my demo :(
> Move show-bake-specific function to show-bake.js

- app/controllers/BaseImageController.scala
- app/data/BaseImages.scala
- app/models/BaseImage.scala
- app/packer/PackerBuildConfigGenerator.scala
- app/views/editBaseImage.scala.html
- app/views/newBaseImage.scala.html
- roles/aws-tools/meta/main.yml
In order to provision redhat boxes for Pluto.
Will default to Ubuntu when not identified or creating a new (or modifying an old) base image.
> Add the concept of Linux distribution

- roles/pluto/tasks/main.yml
@kenoir could you approve? thanks
> adding missed dependency

- roles/s3-ssh-keys/tasks/main.yml
- roles/s3-ssh-keys/templates/update-keys-cronjob.txt.template
(For RedHat only) - simplifies this role.
> Initialise cron job when building ssh keys ami

- roles/s3-ssh-keys/tasks/main.yml
- roles/s3-ssh-keys/templates/initialise-cron-job.sh.template
- roles/s3-ssh-keys/templates/update-keys-cronjob.txt.template
> More ssh keys tidying

- roles/pluto/tasks/main.yml
As this will be done by circleci/cloudformation
> Remove download/install of pluto rpm.

- roles/kong/tasks/main.yml
- roles/ubuntu-init/tasks/main.yml
this time with the branch in the same repo
All as per https://github.com/guardian/amigo/pull/89
@rtyley @LATaylor-guardian
> who wouldn't want a big ulimit?

- roles/ubuntu-init/tasks/main.yml
@paulbrown1982 as per your suggestion, I've applied the nofile limit to the root user specifically
> also give root a bigger open file limit

- roles/ubuntu-init/tasks/main.yml
Reverts guardian/amigo#91
@LATaylor-guardian oops
> Revert "also give root a bigger open file limit"

- roles/ubuntu-init/tasks/main.yml
Reverts guardian/amigo#91
@LATaylor-guardian 😝
> Revert "Revert "also give root a bigger open file limit""

- roles/ubuntu-init/tasks/main.yml
@philwills @LATaylor-guardian @rtyley hopefully this will give all systemd services a bigger no of open files.
> make systemd services have a big ulimit

- README.md
- app/views/newRecipe.scala.html
Added packer dependency to the readme for running locally. This caught me and @jennysivapalan out
Also advises that description is mandatory when creating a recipe
> a couple of small tweaks for first time users

- roles/cloud-watch-logs/files/configure-logs
> Send each log to a different log stream

- roles/nginx+pagespeed/files/nginx.conf
- roles/nginx+pagespeed/files/nginx.service
- roles/nginx+pagespeed/meta/main.yml
- roles/nginx+pagespeed/tasks/main.yml
Small set of fixes for the role
@TBonnin @jfsoul
> Fix permision on the pid file. Adds more compilation properties

- app/controllers/RecipeController.scala
- app/data/Recipes.scala
- app/models/Recipe.scala
- app/views/newRecipe.scala.html
- test/ansible/PlaybookGeneratorSpec.scala
Fix for https://github.com/guardian/amigo/issues/28
DynamoDB doesn't support empty strings, so more a workaround than anything else
> make description for recipes optional

- app/components/AppComponents.scala
- app/controllers/RecipeController.scala
- app/data/Recipes.scala
- build.sbt
This finally allows us to get rid of the bit horrible comment!
> Scanamo 0.9.2

- public/stylesheets/main.css
> Instance usage stats are nicer when they are side-by-side

- app/views/baseImages.scala.html
This seems to have been broken for a while so let's fix it. I'm doing a demo thing this afternoon so I might unilaterally merge this with a promise to fix later if there is any feedback.
> Fix the lack of links for viewing base images

- roles/kong/defaults/main.yml
- roles/kong/files/kong-0.10.1.conf
This .conf is identical to the 0.9.2 version
> Upgrade Kong to 0.10.1

- roles/phantomjs/meta/main.yml
- roles/phantomjs/tasks/main.yml
- roles/unoconv/meta/main.yml
- roles/unoconv/tasks/main.yml
> Add PhantomJS and unoconv

- roles/libreoffice/meta/main.yml
- roles/libreoffice/tasks/main.yml
Ronseal. It's a role for the whole of Libre Office. What more could you ask for?
> Libre Office

- app/controllers/BaseImageController.scala
- app/data/Recipes.scala
- app/views/showBaseImage.scala.html
Address #155 when displaying the details of a base image.
> Show usage of a base image

- roles/mount-drive/tasks/main.yml
- roles/redirect-logs/tasks/main.yml
Add missing user execution bit to GDPR log encryption roles.
> Add user execution to GDPR scripts

- app/data/Recipes.scala
Ronseal. Editing and saving a recipe previously caused an exception if you didn't have a description.
Fixes #147
> Fix saving without a description

- roles/bastion-ssh/meta/main.yml
> Remove bastion dependency on S3 keys

- app/data/BakeLogs.scala
We saw a great number of throughput provisioning errors whilst deleting recipes with a large number of bakes. This will hopefully limit the impact it has, slowing the deletion of logs - but it is asynchronous anyway!
> Batch deletions into groups to prevent overwhelming the bake log

- roles/tesseract4/tasks/main.yml
> Add tesseract language packs

- imageCopier/src/main/scala/com/gu/imageCopier/AmiActions.scala
When we are passed no AMIs that are applicable to us then the AMI lookup finds ALL AMIs ever because our request doesn't filter by AMI. This is not the desired behaviour and causes the lambda to timeout after 30s, rather than exit immediately.
This changes the code flow to short circuit the lookup if no AMIs are passed in.
Thanks @Reettaphant for the heads up.
> Don't do the AMI lookup if we don't have any images

- roles/kong/defaults/main.yml
- roles/kong/files/kong-0.14.0.conf
Next version of Kong: added conf file and changed version in main.yml
> Upgrade Kong to 0.14.0

- roles/kong/files/kong-0.11.2
Copied from previous version. I don't expect the config file to require any changes, but let's stick with this pattern for now
> Kong 0.11.2

- roles/kong/tasks/main.yml
I'm not sure why this stopped working, but adding this step fixes the issue in CODE
> Fix creation of kong dir

- .travis.yml
See [comment](https://github.com/guardian/play-googleauth/pull/66#issuecomment-419874788)
> Switch to openjdk

- roles/aws-kinesis-agent/files/configure-aws-kinesis-agent
- roles/aws-kinesis-agent/tasks/main.yml
So it is suitable on base images that opt not to use it
> MSS-542: Disable Kinesis Agent by default

- roles/tor/meta/main.yml
- roles/tor/tasks/main.yml
> Add Tor role

- roles/openvpn/meta/main.yaml
- roles/openvpn/tasks/main.yaml
Role for baking OpenVPN server and dependencies
> OpenVPN role

- Brewfile
- README.md
- script/setup
to define dependencies and allow them to be installed with one simple script(tm)
> add Brewfile

- app/models/BakeLog.scala
- app/packer/PackerOutputParser.scala
- public/stylesheets/main.css
- test/packer/PackerOutputParserSpec.scala
providing a slightly higher contrast to improve readability of text
**Before**
**After**
> update colours of build log

- README.md
- script/server
Following advice from @akash1810 to give local packer process sufficient authorisation. See in line comments for more detail / context.
> Update on running Amigo locally

- roles/tesseract4/tasks/main.yml
We need to add a new language so why not add them all
> Bring in all tesseract languages

- roles/airflow/tasks/install.yml
Attrs is a library dependency for upcoming changes in the ophan
data lake Airflow implementation.
> Add attrs Python package to Ophan Airflow

- roles/disk-available-cronjob/tasks/main.yml
Shell script courtesy of @aug24
> Use all disks for disk space monitoring

- app/models/BakeLog.scala
- app/packer/PackerOutputParser.scala
- public/stylesheets/main.css
- test/packer/PackerOutputParserSpec.scala
This gives amigo the iTerm2 colour scheme.
> Nicer colours

- ansible/playbook.yaml
- roles/nest-secrets/README.md
- roles/nest-secrets/tasks/main.yml
Adds a [nest-secrets](https://github.com/guardian/nest-secrets) role.
> Add nest-secrets recipe

- README.md
Without a full stop how do you know when to breathe?
> Punctuation is important

- app/views/showRecipe.scala.html
AMIgo already provides details of load balancers and instances running an AMI built by a recipe, which is great. But we don't know which repository the apps run in.
This PR adds a link to a GitHub search, searching for references of the recipe id within `riff-raff.yaml` files in the GitHub organisation makes it easier to know which repos use a particular recipe.
This allows us to find which apps might be affected when editing a recipe.
The URL will go to a search like [this](https://github.com/search?q=org:guardian+xenial-java8-deploy-infrastructure+filename:riff-raff.yaml&type=code).
**Example use case**
I'm looking to deprecate the `s3-ssh-keys` role as ssm has replaced it.
This role was also causing the `xenial-java8-deploy-infrastructure` recipe to [fail to …
> add a link to GitHub search

- roles/oauth2-proxy/defaults/main.yml
- roles/oauth2-proxy/files/oauth2-proxy.service
- roles/oauth2-proxy/tasks/main.yml
Add a new role that will make it possible to install OAuth2 Proxy version 6.x
Rather than altering the existing role, this PR creates a new one.
Steps were adapted from the existing role and have been somewhat tested as part of the [InfoSec Wazuh stack](https://github.com/guardian/infosec-platform/blob/508e46c70ef4a732645e404e8f19a8decab4b9f9/cloudformation/wazuh/wazuh-cluster.yaml#L655).
The existing role is called `google-auth-proxy` and relies on a [GitHub repository](https://github.com/bitly/oauth2_proxy) that is now archived. 
The new role will download oauth2-proxy from the [official fork](https://github.com/oauth2-proxy/oauth2-proxy) which is being maintained and developed:
- The last release of `bitly/oauth2_proxy` was v2.2 in April 2017. 
- The last release of …
> Add new oauth2-proxy role for version 6.x

- renovate.json
This adds a single Issue from which to track dependency updates suggested by Renovate. See the docs https://www.whitesourcesoftware.com/free-developer-tools/blog/introducing-renovates-master-issue/ for more details
> add renovate master issue

- README.md
Fixed typo in line 41 of this `Readme.md`file
There is no need of test. No collateral damage.
Just a simply look of line 41 probes that minor mistake on documentation
There is no break on code.
No needed it.
> Minor fix (line 41)

- script/ci
We've currently manually defined the build step in CI. This makes it impossible to tweak across branches.
This change follows our recommendations and creates a `script/ci` file to run in CI instead.
See:
- https://github.com/guardian/recommendations/blob/master/continuous-integration.md
CI needs updating, once it has CI should pass.
We're able to tweak the build process across branches. For example, we can add some CDK snapshot testing on the branch that migrates the CFN YAML to CDK.
> chore: Add script to execute in CI

- cloudformation.yaml
In order to produce a small change set in the [move to GuCDK](https://github.com/guardian/amigo/pull/598), ensure all resources that [support tagging](https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html) have the identity tags.
CDK applies tags in alphabetical order, so reorder some of the existing tags to meet this criteria.
See [here](https://github.com/guardian/amigo/commit/5a4d6537e00ed19c4970eca0af196caabdb08532) for more context.
n/a
It is easier to spot dangerous changes GuCDK will make to the stack as there will be less noise in the change set.
> chore: Add App, Stack, Stage tags to taggable resources

- cdk/lib/__snapshots__/amigo.test.ts.snap
- cdk/lib/amigo.ts
- cloudformation.yaml
Builds on #612 and #598.
Moves the Packer policy over to the CDK defined stack.
Deploy this branch to CODE and perform a bake. The bake should complete successfully.
We move closer to a CDK only template and have tighter access policies.
> feat: Define Packer policy within CDK

- cdk/lib/amigo.ts
This is a no-op (as demonstrated by the snapshot not changing) and just improves clarity.
Easiest to review [w/out whitespace](https://github.com/guardian/amigo/pull/620/files?diff=split&w=1).
> refactor: Reduce the number of individual calls to `attachToRole`

- cdk/package.json
- cdk/yarn.lock
We don't have Dependabot on this repo yet. This change bumps all the libraries using `yarn upgrade-interactive --latest`, just to keep things up-to-date.
CI should continue to pass.
> chore(deps): Update deps to the latest available

- cdk/lib/__snapshots__/amigo.test.ts.snap
- cdk/lib/amigo.ts
- riff-raff.yaml
This change uses the `GuPlayApp` pattern to define the ASG, ALB etc for AMIgo 🎉 . It's pretty big, I'm struggling to break it down - help wanted!
With this change we are creating a new load balancer that will run in parallel to the current one. This will allow us to perform a zero-downtime migration via a three step dance:
1. Run two load balancers
2. Update the CNAME to point to the new load balancer
3. Remove the old load balancer
There are no deletions being made in this change (the change set JSON is below), so we should not incur any downtime.
It's worth noting that instances launched in the new ASG are not configured exactly the same as the current instances. The current instances can be [reached directly on port 9000](https://github.com/guardian/amigo/blob/ad138c93b63b5fa01b8f44399b …
> feat: Use the `GuPlayApp` pattern

- roles/cloudwatch-hardware-monitoring-cronjob/README.md
...with some useful guidance on aws permissions and common parameters
> Update hardware monitoring role readme

- roles/teamcity-agent/defaults/main.yml
- roles/teamcity-agent/tasks/main.yml
It looks like nvm has moved into the [`nvm-sh` organisation](https://github.com/nvm-sh/nvm#installing-and-updating), so install it from there.
- Build a TeamCity agent
- Witness it succeed
Keeping up to date.
n/a
> install latest nvm from an up to date source

- roles/cdk-base/README.md
List instance tag and IAM requirements for the `cdk-base` AMIgo role. Also provide CFN YAML snippets for ease of adoption.
Does it [read](https://github.com/guardian/amigo/blob/aa-cdk-base-readme/roles/cdk-base/README.md) well?
Adoption of this role is that much easier.
I've not checked the permissions are exhaustive...
> docs: Document requirements of `cdk-base`

- app/data/Bakes.scala
- app/housekeeping/BakeDeletion.scala
An attempt to catch any errors in the bake deletion process, which might explain why we are not getting any housekeeping notifications sent and why records in Dynamo are not being deleted.
I have been able to successfully run the process locally, so my money is on corrupt data in Dynamo 🎲 .
> Catch and log errors in bake deletion housekeeping job

- .github/workflows/ci.yaml
Use the latest version of [action/setup-java](https://github.com/actions/setup-java) and enable [sbt caching](https://github.com/actions/setup-java#caching-packages-dependencies)
> Add caching of SBT artefacts

- roles/puppeteer/tasks/main.yml
This PR aims to resolve an issue preventing `time-machine` from being migrated to Ubuntu Jammy. When installing puppeteer to the root directory, an error is encountered: 
```
[2023-04-06 14:08:41] ophan-time-machine-jammy-arm-CDK: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/npm install ''", "msg": "npm ERR! Tracker \"idealTree\" already exists
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2023-04-06T14_08_40_151Z-debug-0.log", "rc": 1, "stderr": "npm ERR! Tracker \"idealTree\" already exists
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2023-04-06T14_08_40_151Z-debug-0.log
", "stderr_lines": ["npm ERR! Tracker \"idealTree\" already exists", "", "npm ERR! A complete log of this run can be found in:", …
```
> Fixes an issue with npm installing puppeteer onto Jammy instnaces

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/image-copier-lambda.test.ts.snap
- cdk/lib/image-copier-lambda.test.ts
- cdk/lib/image-copier-lambda.ts
- imageCopier/README.md
This proved challenging to deploy recently, so updating the docs to help here.
cc @NovemberTang and @tjsilver who did this recently and may have thoughts on how this could be improved.
n/a - docs change, though someone could step through it if keen.
Easier deployment in future.
> Improve Image Copier docs

- roles/whisper-cpp/tasks/main.yml
- Changes whisper-cpp role so that it downloads models medium, small, and base in addition to large. On the investigations team we are testing these models for performance and accuracy. Later we'll settle on one model and remove the download of the others.
- Info on these models is [here](https://github.com/ggerganov/whisper.cpp/tree/master/models).
- adds command to role changing ownership of everything inside `/opt/whisper` to user `ubuntu`
- tested with locally with multipass
- tested in code with [this bake](https://amigo.code.dev-gutools.co.uk/recipes/investigations-ocrmypdf/bakes/9)
> **Note**
> If this change adds, updates or removes a role or recipe please note that in your PR and assign appropriate reviewers for the team that will be impacted by those changes.
> Add models to role whisper-cpp role

- build.sbt
Update the AWS SDK and Anghammarad dependencies to (hopefully) resolve some Snyk reported high vulnerabilities being brought in transitively.
> chore(deps): Update AWS SDK and Anghammarad

- app/controllers/Login.scala
- app/controllers/RecipeController.scala
Adding info log messages for the following activities:
- recipe creation
- recipe editing
- recipe deletion
- user logging in
Tested this in CODE environment 
We realised that one of our recipes was deleted but couldn't find any detail in the logs when/how that happened. It would be useful to have logs for these scenario. 
> **Note**
> If this change adds, updates or removes a role or recipe please note that in your PR and assign appropriate reviewers for the team that will be impacted by those changes.
> Add logging for user login and for recipe creation, edit and deletion

- app/views/fragments/usagesColumn.scala.html
This resolves a copy paste mistake added in https://github.com/guardian/amigo/pull/1507
> Fix hover over text for usages column

- build.sbt
Updates the following dependencies:
- AWS v1 SDKs from 1.12.788 to 1.12.791
- AWS v2 SDKs from 2.31.78 to 2.34.0
- `com.gu.anghammarad-client` from 5.0.0 to 6.0.0
- `com.gu.simple-configuration-ssm` from 6.0.0 to 7.0.1
- `com.gu.play-secret-rotation.play-v30` from 13.2.0 to 15.1.0
- `com.gu.play-secret-rotation.aws-parameterstore-sdk-v2` from 13.2.0 to 15.1.0
- `com.gu.play-googleauth.play-v30` from 20.1.0 to 26.0.0
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/e276e015-3821-4a4a-9df3-335177e70a41) and started a bake successfully.
This should resolve https://github.com/guardian/amigo/security/dependabot/65.
> **Note**
> If this change adds, updates or removes a role or recipe please note that in your PR and assign appropriate reviewers for the team that will be …
> chore(deps): Dependency updates
