guardian/amigo

app/packer/PackerBuildConfigGenerator.scala

We disabled this because they didn't have a package for Xenial.
Now they do, so we can get a consistent Ansible version (currently 2.1.0.0-1) on all Ubuntu versions.
Good news for @Reettaphant! This means you don't need to do your workarounds for Ansible 1.x any more. e.g. you can now use `unarchive src=http://...`

Install Ansible from the PPA

---

roles/logstash/defaults/main.yml
roles/logstash/meta/main.yml
roles/logstash/tasks/main.yml
roles/logstash/templates/logstash.service.template

CAPI still needs Logstash to send non-application logs (GC logs, Elasticsearch slowlog, etc.)
This role has been tested in DEV and seems to work as expected, but may need minor tweaks after I try it with the CAPI apps.

Add a role to install Logstash

---

cloudformation.json

This allows Packer to start a machine with an instance profile. See the bottom of https://www.packer.io/docs/builders/amazon.html

Add `iam:PassRole` to packer permissions

---

app/components/AppComponents.scala
app/data/BakeLogs.scala
app/data/Bakes.scala
app/data/BaseImages.scala
app/data/Dynamo.scala
app/data/DynamoFormats.scala
app/data/Recipes.scala
app/models/AmiId.scala
app/models/BakeId.scala
app/models/BakeStatus.scala
app/models/BaseImageId.scala
app/models/RecipeId.scala
app/models/RoleId.scala
app/models/StringId.scala
app/views/editRecipe.scala.html
build.sbt

* Upgrade Scanamo
* Switch to Scanamo's table API
* Refactor the Dynamo object accordingly
* Add a custom `DynamoFormat[Option[T]]` to work around a change in Scanamo behaviour
* Bump Scala version
At this point I'm not using Scanamo's Free monad goodness as nature intended, but I will experiment with that soon as part of the preparation for my Lambda World talk.
There are still a couple of places where we use the raw Dynamo API instead of Scanamo. These are blocked on Scanamo issues (guardian/scanamo#61, guardian/scanamo#62).
I've tested all the major functionality locally and everything seems to work.

Upgrade Scanamo to 0.7

---

build.sbt

This fixes an AWS SDK version conflict caused by the Scanamo upgrade. Configuration-magic doesn't make any calls to the EC2 API when you're running on your local machine, so the problem only manifested itself in production. My favourite kind of bug.

Upgrade configuration-magic

---

roles/kong/defaults/main.yml
roles/kong/files/truncate-ratelimiting_metrics.sh
roles/kong/tasks/main.yml

This script runs as a nightly cron job and deletes old entries from one of Kong's DB tables. Without it, the table will grow indefinitely until the DB machine fills its disk.
Also install the `psql` command on the Kong machine.
This has been tested in CODE.

Add a housekeeping script for Kong

---

app/data/Bakes.scala

This is a regression introduced during the Scanamo upgrade

Fix a missing exec() call

---

roles/kong/files/truncate-ratelimiting_metrics.sh
roles/kong/tasks/main.yml

- Run truncate script every two hours rather than every 24 hours to reduce impact on Postgres.
- Rewrite query to make it clearer how to limit a delete query.
see: http://docs.ansible.com/ansible/cron_module.html for ansible cron docs.

Amigo - modify kong truncate-ratelimiting_metrics script.

---

roles/s3-ssh-keys/tasks/main.yml

As redhat6, which pluto runs on, doesn't have systemd. The cronjob version will need to be kicked off after the instance comes up which isn't as nice as systemd but does the job.

When running on RedHat, create cronjob files instead of a systemd process to update keys.

---

roles/disable-missed-daily-tasks/files/apt-daily.timer.conf
roles/disable-missed-daily-tasks/tasks/main.yml

With Xenial there is a task that does apt related tasks at boot time. This can mean that attempts to install packages at boot time can fail resulting in instances not coming up. See this for some more details: http://stackoverflow.com/questions/36896806/how-can-i-be-sure-a-freshly-started-vm-is-ready-for-provisioning
This PR adds a new role that disables this boot time behaviour so that provisioning of instances never fails (because of this at least).
The intention is to add this to the base Xenial image to avoid surprising people.

New role that disables missed daily tasks at boot time

---

roles/pluto/tasks/main.yml

@kenoir 
Portal has an annoying bug, whereby if a plugin fails to start up properly because of an exception the actual error is not shown in the log, but a generic one about "model User does not exist."
This introduces a patch which prevents the secondary exception and thereby allows the actual problem to be logged.  I use it for all testing and it is in place on the FourthPortalDev image that we use.

adding logging bug patch

---

roles/filebeat-logstash-kinesis/files/elastic.repo
roles/filebeat-logstash-kinesis/meta/main.yml
roles/filebeat-logstash-kinesis/tasks/main.yml
roles/filebeat-logstash-kinesis/templates/filebeat-kinesis-exporter.conf.template
roles/filebeat-logstash-kinesis/templates/filebeat.yml.template
roles/java8/tasks/main.yml

In order to ship logs from Pluto to the editorial-tools ELK stack.

Filebeat -> Logstash -> Kinesis

---

roles/install-rsyslog-config/meta/main.yml
roles/install-rsyslog-config/tasks/main.yml
roles/install-sysfsutils/tasks/main.yml
roles/mongo30/tasks/main.yml

As discussed I've moved rsyslog and sysfsutils to mongo30.
@Reettaphant @philmcmahon I can merge this into @Reettaphant branch if you're happy with this.

Move install of rsyslog and sysfsutils to mongo30

---

app/components/AppComponents.scala
roles/cloud-watch-logs/README.md
roles/cloud-watch-logs/files/aws-region
roles/cloud-watch-logs/files/awslogs.conf
roles/cloud-watch-logs/files/configure-logs
roles/cloud-watch-logs/meta/main.yml
roles/cloud-watch-logs/tasks/main.yml

This allow us to bake images with the cloudwatch-log agent.
It also provide a utility script to reduce the boiler plate in the user-data within the cloudformation.
It assumes the distribution is using systemd
The readme should explain it all, so if it isn't clear please let me know I'll do my best to improve it.

Cloudwatch logs role

---

app/models/CustomisedRole.scala

Updated as part of work to write a role to allow installation of elasticsearch plugins. It needs to be possible to have `/` in a parameter value. E.g. `plugins:elasticsearch/elasticsearch-cloud-aws/2.7.0`

Allow forward slash in parameter values.

---

app/models/CustomisedRole.scala

Follow up from this [PR](https://github.com/guardian/amigo/pull/108). Elasticsearch plugins can have `.` in them so it needs to be possible to specify parameter values with a `.` in order to write an elasticsearch install plugins role.

Allow parameter values to have a dot.

---

app/controllers/BaseImageController.scala
build.sbt

Fixing the 'Reference to uninitialized values' error occurring when trying to create/edit a base image: https://amigo.gutools.co.uk/base-images/new
```
[warn] /.../amigo/app/controllers/BaseImageController.scala:77: Reference to uninitialized value amiId
[warn]       "amiId" -> amiId,
...
[warn] /.../amigo/app/controllers/BaseImageController.scala:83: Reference to uninitialized value amiId
[warn]       "linuxDist" -> linuxDist
...
```
Also adding compiler options like `-Xfatal-warnings` to prevent this kind of issue to happen again

Fix: Reference to uninitialized values + add compiler options

---

roles/elasticsearch-housekeeping-cronjob/meta/main.yml
roles/memory-disk-autoscaling-monitoring-cloudwatch/README.md
roles/memory-disk-autoscaling-monitoring-cloudwatch/meta/main.yml
roles/memory-disk-autoscaling-monitoring-cloudwatch/tasks/main.yml

Role was introduced in a previous [PR](https://github.com/guardian/amigo/pull/113) but was not actually needed. Tidying up.

Remove role that was created but never used.

---

roles/logstash/tasks/main.yml

This command does not execute without quotes

Add quotes around command

---

README.md
docs/riffraff-integration.md

Added some (hopefully helpful!) documentation on how to use Amigo baked instances with RiffRaff.
This is a first attempt to add some more documentation on how to use Amigo baked AMIs in Riffraff. I hope it makes some sense! Would appreciate any feedback! @sihil @adamnfish @TBonnin !

Add Riffraff integration doc

---

app/views/showBake.scala.html
public/stylesheets/main.css

Fixing a small navigation annoyance. Once on a bake page it is not possible to directly come back to the recipe. [Example](https://amigo.gutools.co.uk/recipes/ubuntu-xenial-java8/bakes/196)
This patch is adding a link to the recipe as well as reorganising the bake info
Before:
After:

Bake: Add link to go back to recipe + reorganize bake info

---

app/controllers/RoleController.scala
app/data/Roles.scala
app/models/Dependency.scala
app/views/fragments/dependencyList.scala.html
app/views/roles.scala.html
public/stylesheets/main.css
test/data/RolesTest.scala

In the list of dependencies for each role, show also the transitive ones.
Add a tab with all the Roles and Recipes that use the specific Role.
Before:
For example previously the `disk-available-cronjob` role would show only the `cloud-watch-motitoring` as a dependency.
After:
It would also show `apt` and `perl-useful-packages` which are dependencies of `cloud-watch-motitoring`.
"Used by" tab:

Add transitive role dependencies

---

app/views/baseImages.scala.html
app/views/editRecipe.scala.html
app/views/recipes.scala.html

This sorts the recipes in alphabetical order (at the moment I think it's related to the order in dynamo?). Fixes #130.
Also I've added a link to this online tool that helps make sense of quartz expressions: http://www.freeformatter.com/cron-expression-generator-quartz.html

Add link to helpful cron tool and sort recipes

---

roles/elasticsearch-housekeeping-cronjob/README.md
roles/elasticsearch-housekeeping-cronjob/files/housekeeping.sh
roles/elasticsearch-housekeeping-cronjob/tasks/main.yml

NB: I've applied the same changes on the production boxes themselves.
Fixes a problem where the cron scripts to delete indices were not running so the ES boxes ran out of disk space.
Due to the CLI for Curator changing significantly (and with [potential incompatibility problems](https://pypi.python.org/pypi/elasticsearch-curator#compatibility-matrix) as well), I've pinned us to the older version and added a note that this role only works with the older ElasticSearch.
I've also bumped up the retention period to 14 days now that we have space.

Pin version of curator and bump retention time to 14 days

---

README.md

it's moved to https://www.packer.io/intro/getting-started/install.html by the looked - the old one was 404ing.

correct packer url in readme

---

roles/bastion-ssh/README.md
roles/bastion-ssh/files/sshd_config
roles/bastion-ssh/tasks/main.yml

I've copied across the configuration for `sshd` on a bastion instance from how it is done by the identity team.
- Modified `sshd_config` to do things like listen on a different port etc
- Remove `ubuntu` from sudoers
I didn't copy across some entries that made `/home/ubuntu/.ssh` owned by root and the `authorized_keys` file immutable, since that would conflict with the existing Amigo `s3-ssh-keys` role which automatically updates the file.

Bastion SSH role

---

roles/disable-missed-daily-tasks/files/apt-daily-upgrade.timer.conf
roles/disable-missed-daily-tasks/tasks/main.yml

This is similar to what is disabling the apt-daily task, and should help with the issue Jacob and John were seeing: https://github.com/guardian/membership-frontend/pull/1716

Skips running missed apt-daily-upgrade tasks on startup

---

roles/cloud-watch-logs/meta/main.yml

pip is installed if not already installed by the cloudwatch logs script on init. This slows down boot and can cause the `dpkg` lock to be taken. By pre-installing it we can avoid these issues.

Install pip if installing cloudwatch logs

---

roles/disable-missed-daily-tasks/tasks/main.yml

To resolve:
`FAILED! => {"changed": false, "checksum": "99df8a48a3b0b4e327d365a9048efe2993561e9f", "failed": true, "msg": "Destination directory /etc/systemd/system/apt-daily-upgrade.timer.d does not exist"}`

Create missing directory

---

roles/bastion-ssh/README.md
roles/bastion-ssh/meta/main.yml

This avoids the problem building recipes that use both roles. If s3-ssh-keys runs after the bastion role it can't add the ssh user because sudo has been revoked.

Make the Bastion SSH role depend on s3-ssh-keys

---

roles/bastion-ssh/README.md
roles/bastion-ssh/tasks/main.yml

It appears the bastion ssh role can interfere with other roles that require sudo access because it removes ubuntu from sudoers.  This is a quick fix for that, which removes that task from the role.
Perhaps the better solution would be to implement some notion of priority to the roles in a recipe and give the bastion role a low priority so that it is executed last.  I would be happy to make those changes subsequently if we think it might be a useful feature? cc: @philwills

Keep ubuntu in sudoers for bastion role

---

README.md
roles/s3-ssh-keys/README.md
roles/s3-ssh-keys/templates/install-keys.sh.template

See s3-ssh-keys README change but basically, this supports providing a list of teams for the ssh prefix argument. The immediate use case if for Frontend where it is helpful to be able to re-use existing Github SSH teams (e.g. Identity-SSH-Access) rather than duplicating them.
Note, I didn't realise the full power of Jinja was available so spent a disappointing amount of time trying to coerce a Python list string representation into something usable in bash. :(

Support multiple teams for ssh access

---

app/packer/PackerBuildConfigGenerator.scala
cloudformation.yaml

To make it easier to test AMIgo builds without having to perfect your local setup I've created a CODE version of AMIgo. This PR makes a few tweaks to make that possible and improve CFN practices.
In particular:
- The BuiltBy tag is set to `amigo` when PROD but `amigo-$stage` when any other stage. In the real world people are finding AMIs without including the AmigoStage tag. This modification will ensure that people don't accidentally pick up a test image from CODE.
- Replacing hardcoded `PROD` with `${Stage}` in the CFN template
- The instances and builders have been moved into the Private VPC subnet and access to the instances is now over the DirectConnect link
Once this is merged I'll retrospectively update PROD and double check it all still works as expected.

Some tweaks to allow us to have an AMIgo CODE

---

app/models/BaseImage.scala
roles/chrony/meta/main.yml
roles/chrony/tasks/main.yml
roles/ubuntu-init/meta/main.yml

AWS have announced a new Time Sync Service (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) that is available on link local addresses.
- The Link Local address is only available inside VPCs. The change retains other NTP servers for any legacy infrastructure that still isn't in a VPC and simply prefers the new link local address when available
- It will no longer be necessary for instances to be able to access the internet for time sync
- Chrony is now the preferred time sync service so this is now used instead of NTP
- This PR introduces configuration to use the link local config in a new `chrony` role, although it also switches the old `ntp` role out in the `ubuntu-init` so when this PR is merged it will immediately impact any new image
The `chronyc sources -v` command …

Switch over to AWS link local NTP

---

roles/enhanced-networking/tasks/main.yml

There is a problem with the enhanced-networking driver (see https://stackoverflow.com/questions/44833346/cant-get-ixgbevf-to-build-on-current-ubuntu-ami) that causes build failures on later linux kernels.
This has come to light when trying to use the latest Xenial AMI as a base in AMIgo. This small patch fixes it by commenting out the check in the source code.
This has been tested on CODE (works aside from some warning messages): https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-java8/bakes/5

Patch enhanced-networking for later kernel numbers

---

roles/mount-drive/tasks/main.yml
roles/redirect-logs/tasks/main.yml

Mistakenly missed out the directory in the task copy.

Fix bad GDPR tasks

---

roles/cloud-watch-logs/README.md
roles/cloud-watch-logs/files/configure-logs

I'm trying to add auth.log to cloudwatch, and the date format isn't quite the same as the default play log.
This should allow us to pass whatever format we want at the time the image is booting, pushing any log, including system logs.

add optional date format for cloudwatch log parsing

---

roles/aws-await-tags/README.md
roles/aws-await-tags/tasks/main.yml
roles/aws-await-tags/templates/await_tags.sh

We have seen some issues in PROD on Ed Tools caused by tags not being available when the user data script is run.
The real fix is to change the apps to not call Describe Tags to find out Stack, App, Stage etc. In the meantime we can use this role that will block calling the main script until tags are available (or 1 minute has elapsed).

Await aws tags

---

roles/java8/tasks/main.yml

This change adds an action to role `java8`, that only affect Trusty (14.04), by adding a missing repository preventing the role to fail when running recipes on that image.

Add open JDK repository on Trusty (14.04)

---

roles/ssm-agent/README.md
roles/ssm-agent/tasks/main.yml

This change creates the role ssm-agent which downloads and install AWS's ssm agent (https://github.com/aws/amazon-ssm-agent).
To be used with the security-hq recipe.

Introduce new role for installing AWS's ssm agent

---

imageCopier/imageCopier.yaml
imageCopier/imageCopierKmsKey.yaml

The image copier lambda requires a KMS key unique to each account it runs in.
The best way to do this is to create an additional stack that only creates KMS keys for the Image copier and then deploy this second stack in all accounts that use the image copier lambda. 
The cloudformation added here describes and creates that second stack.

New stack to handle KMS keys for Image Copier

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/controllers/RecipeController.scala
app/packer/PackerRunner.scala
app/prism/Prism.scala
app/prism/RecipeUsage.scala
app/schedule/ScheduledBakeRunner.scala
app/services/PrismAgents.scala
app/views/showRecipe.scala.html
test/prism/PrismSpec.scala
test/prism/RecipeUsageSpec.scala

It's pretty confusing that the usage and bake history don't currently display copies of AMIs that are in other accounts. This fixes that by adding a little more magic to both of them.
For example the bake history now looks like this:
As an added bonus I fixed the copy to clipboard functionality so that it works!
In short I've added a new prism agent that queries prism for all AMIs that have the `CopiedFromAMI` tag set. That is the tag that is set with the original AMI ID when the lambda kicks off a copy. This is then correlated with the list of AMIgo AMI IDs to create the list of copies.
In order to display human friendly accounts I've also expanded the data gathered from prism for accounts to include the name as well as number. This can then be used as a lookup table.

Make encrypted copies visible in AMIgo

---

imageCopier/imageCopier.yaml

Some projects need to specify the KMS key to use when copying the AMI

Override KMS key

---

riff-raff.yaml

I was trying to work out why an earlier deploy worked when it shouldn't and realised that the public ACL flag is being set by default.

Don't upload the lambda code with public ACL flag

---

roles/ssh-deny-root/README.md
roles/ssh-deny-root/tasks/main.yml
roles/ssh-ubuntu-only/README.md
roles/ssh-ubuntu-only/tasks/main.yml
roles/ubuntu-init/meta/main.yml

Two new roles:
Allow only ubuntu to ssh on to the box.  This is intended for teams who have adopted the ssm-scala approach to temporary ssh credentials.
Do not allow root to ssh on to the box.  This is a patch for a security risk and should be adopted everywhere.

Sshd security

---

roles/s3-ssh-keys/templates/install-keys.sh.template

We're seeing our `authorized_keys` file contain many hundreds of repeated keys because it looks like we are appending instead of overwriting to /tmp/authorized_keys.
~Requires testing.~ Tested.

Overwrite temp keys file instead of append

---

roles/s3-ssh-keys/templates/install-keys.sh.template

PR #180 introduced a new bug for the case when more than one team prefix is declared - the docs for `s3-ssh-keys` say this is supported:
```
ssh_keys_prefix: [Team-NameA, Team-NameB]
```
...but when overwrite (`>`) is used rather than append (`>>`) for concatenating together the keys of multiple teams this means that only the last team wins - the keys from all other teams are overwritten.
Instead in this commit we use a unique temporary aggregating directory, to allow us to join various key files together, without accumulating unwanted previous versions of the key data.
cc @amyhughes

Fix s3-ssh-keys role for when more than one team is declared

---

roles/friendly-hostnames/README.md
roles/friendly-hostnames/defaults/main.yml
roles/friendly-hostnames/files/set-friendly-hostname.sh
roles/friendly-hostnames/meta/main.yml
roles/friendly-hostnames/tasks/main.yml

The feature sets the hostname for your server and applies an AWS "Name" tag. The name is chosen from a list of names, defaulting to ~3000 names at 
```
https://s3-eu-west-1.amazonaws.com/ophan-dist/ophan/elasticsearch/hostnames.txt
```

Add friendly-hostnames role for giving servers human readable names

---

roles/browser-testing/README.md
roles/browser-testing/tasks/main.yml

locates the latest version from https://chromedriver.storage.googleapis.com/index.html rather than relying on parameters

get latest chromedriver version in browser-testing role

---

roles/logstash-deb/README.md
roles/logstash-deb/tasks/main.yml

I've raised a PR against the `logstash-input-kinesis` plugin but until it is merged this provides a way to build an AMI with a custom plugin. The custom plugin is hosted in the amigo data S3 bucket and retrieved and installed from that location during build time.
This is much the same method that we use to install packages from S3.
This has been tested on AMIgo code and found working.

Install logstash plugins from S3

---

roles/aws-await-tags/templates/await_tags.sh

Facia uses the base role that has await tags in it but does not have permission in the CloudFormation to call describe-tags in the API. It doesn't need it since it injects the stack, app and stage through the launch configuration. Unfortunately, the script still waits a minute even though each call fails because it doesn't have permission.
This PR changes the script to exit early if we don't have permission. If we have permission but the tags are not yet present we get back an empty list so it still waits as expected.

Exit immediately if we are unable to call describe-tags

---

imageCopier/imageCopierKmsKey.yaml

AWS are making changes to the way that ASGs gain access to other AWS resources. Of note an ASG used to be able to magically access any KMS CMK and this is no longer true. 
This change gives the default ASG Service Linked Role access to the KMS key that we are using to encrypt root volumes.

Allow access to this key from the default ASG service linked role

---

app/controllers/RecipeController.scala
app/prism/Prism.scala
app/prism/RecipeUsage.scala
app/services/PrismAgents.scala
app/views/recipes.scala.html
app/views/showRecipe.scala.html
app/views/showUsage.scala.html
conf/routes
test/prism/PrismSpec.scala
test/prism/RecipeUsageSpec.scala

The usage information in AMIgo is not surfaced in a particularly friendly way. As a first step towards automatically cleaning up AMIs, this adds pages that break down exactly where a particular recipe is used.
Main features:
- Linked to from the recipe index / recipe page
- Identifies copies to alternate accounts
- Shows instances and launch configurations
- Links from instances / launch configurations go to the prism API (not very friendly, but better than nothing)

Add a usage page for recipes

---

app/components/AppComponents.scala
app/controllers/RecipeController.scala
app/housekeeping/MarkOldUnusedBakesForDeletion.scala
app/prism/RecipeUsage.scala
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala

This was not being used anyway so is a bit of a code clean up
This adds a new housekeeping task that runs each hour and will find bakes over **30 days old** that are **not in use**. To prevent hitting DynamoDB too hard and running into throughput exceptions, only the first 100 of the old unused bakes will be marked for deletion upon each run.
We have never deleted bakes before, so it may take us a while to get under 100! Once we do, it is unlikely we will get over 100 again, so scheduling this task for once an hour and taking 100 seemed like a reasonable approach that allows us to avoid scaling up the DynamoDB throughput, or adding in a `Thread.sleep(...)` that probably wont matter after the first run...
This change means that any bakes marked as deleted will be deleted by the other …

Automatically delete any bake that is older than a month and is not in use

---

build.sbt
riff-raff.yaml

The world is much better when your deploy matches up with the cloudformation. Since the CFN template for AMIgo is in the codebase we should definitely deploy it automatically.

Automatically deploy AMIgo cloudformation at deploy time

---

project/plugins.sbt

When converting to DEB some snowflake logic for Travis got lost, this brings it back by adopting version 1.1.8 of the plugin which includes https://github.com/guardian/sbt-riffraff-artifact/pull/49

Bump SBT riff-raff artifact plugin for Travis fix

---

app/notification/LambdaDistributionBucket.scala
imageCopier/imageCopier.yaml

A bit of a hack that allowed us to force out a new version of the lambda to all the stacks in the stack set (by virtue of changing the s3 key).
There is another PR (https://github.com/guardian/amigo/pull/201) that should solve this properly but for the time being this let us fix a bug.
Note that the proposed riff-raff.yaml doesn't deal with dependencies quite as you expect as each stack/region combination does its own dependency resolution and Riff-Raff doesn't support dependencies across stacks.

Change the name of the S3 key to force reload

---

app/packer/PackerRunner.scala

When in debug mode packer needs to run in a directory it can write to in order to output the private key for the instance it is building. This should do the trick. Hopefully it won't break anything else 🤞

Run packer with /tmp as the working directory so it can write to it

---

app/controllers/RecipeController.scala

Quick fix to deschedule a recipe that was scheduled to build automatically when it is deleted.

Deschedule recipes from automatic bakes when deleting

---

app/components/AppComponents.scala
app/controllers/HousekeepingController.scala
app/data/Bakes.scala
app/data/Recipes.scala
app/housekeeping/MarkOldUnusedBakesForDeletion.scala
app/housekeeping/MarkOrphanedBakesForDeletion.scala
app/models/BakeId.scala
app/views/housekeeping.scala.html
app/views/layout.scala.html
conf/routes
test/housekeeping/MarkOrphanedBakesForDeletionSpec.scala

Orphaned bakes may exist for a few reasons... 
If a recipe has been deleted from a table but not the associated bake, then these lonely bakes will linger on and never get picked up by the housekeeping... Until now
Something interesting was happening with the DEV DynamoDB table and there were read errors so I have decided to surface these so the housekeeping task can decide what to do.
I have set the `FAULT_TOLERANCE` to `0` for now, which means that the housekeeping scheduler will abort in DEV mode:
If the housekeeping task does not get stopped it should happily mark all the orphaned bakes for deletion. Once marked the deletion housekeeping should finish off doing the clean up.
This includes a form that manually allows you to mark the orphaned bakes for deletion. This is helpful if your …

Add housekeeping task for orphaned bakes and a housekeeping UI

---

app/controllers/BaseImageController.scala

AWS have increased the length of resource IDs. They are now a 17 char string prefixed by the resource ID (in this case `ami-`).
This adjusts the form validation accordingly.

Increase max length of AMI ID

---

app/views/showBake.scala.html
public/javascripts/show-bake.js

The auto-scroll logic queues the animations rather than scrolling to the bottom immediately. This makes the page 100% unusable because after many 10s of updates have come through you're waiting for
literally minutes, unable to scroll the output while the jQuery animation queue completes. Without the queue this actually follows the output and you'll never have to wait more than `$animationDuration` (currently 500ms) before you can regain control.
Labelling the checkbox `tail -f` makes it unclear whether this refers to scrolling the div, or actually obtaining the log contents. It makes it feel like unticking this would stop the log loading at all. Auto scroll makes it clear we're just talking about the interface.

Improve "show bake" page

---

roles/kong/files/kong-0.14.0.conf

Subtly broken by this change https://github.com/Kong/kong/blob/master/UPGRADE.md#admin-api-1
It prevents outside access to kong's admin api, from kong v0.12.
The admin api needs to be accessed from bonobo, and we use security groups to keep this port secure.

Fix kong listen address

---

roles/puppeteer/README.md
roles/puppeteer/tasks/main.yml

Ophan's Time Machine (https://dashboard.ophan.co.uk/time-machine) needs `Puppeteer` in order to be able to take full-page web screenshots - it used to use `phantomjs` but that is a dead project...
https://github.com/guardian/ophan/issues/2952

Puppeteer - Headless Chrome Node API

---

roles/node/README.md
roles/node/tasks/main.yml

added additional parameters for the 'node' role to allow downloading from nodejs.org (rather than the current unofficial nodesource.com)
paired with @philmcmahon

new parameters for the 'node' role to allow downloading from nodejs.org

---

README.md
roles/packages/README.md
roles/packages/tasks/main.yml

Packages such as http://pm2.keymetrics.io/docs/usage/install-as-deb/ require the key to be installed from the ubuntu keyserver. This change adds the option of specifying a key in this way, rather than via a url.
It also adds some documentation for testing amigo roles with vagrant, something I found saved a lot of time recently.

Support adding keys from keyserver, extra docs

---

roles/node/README.md
roles/node/tasks/main.yml

This adds a step to add a symlink to the node `bin` directory (containing node, npm etc.) in /usr/local so that it can be referenced easily (without knowing the node version).
It also adds the functionality to allow the role to install npm packages globally. Arguably this belongs in a separate role, but due to the dependency between the [npm ansible step](https://docs.ansible.com/ansible/devel/modules/npm_module.html) and `npm` it is bit of a pain to separate this out. This doesn't feel like a terrible place to put this step - as it is optional, and I suspect will be used fairly often to install node and [pm2](http://pm2.keymetrics.io/).
Finally, I've removed the 'alternative' option of specifying the nodejs.org relative path on the basis that it adds quite a bit of complexity, and will …

Allow node role to install npm packages

---

roles/language-tool-ngrams/defaults/main.yml
roles/language-tool-ngrams/tasks/main.yml

The ngram data for language tool is 8.5Gb and is impossible to download and extract within a reasonable timeframe at boot time. As such it is desirable to bake this into an AMI.
This is a hardcoded role just for doing this task. In order to shorten bake time we do a piped download and extract.

Pre-bake ngram data

---

roles/aws-kinesis-agent/README.md
roles/aws-kinesis-agent/files/configure-aws-kinesis-agent
roles/aws-kinesis-agent/tasks/main.yml

Ubuntu reset /var/run permissions after restart (between ami build and run), so the agent fails to be able to use its checkpoint file.
If file is in /opt it should be fine, happy to change to another location if preferred, but this folder is already created as part of the installation.
Revised to take a stream parameter instead of app, stack, stage as the kinesis stream is unlikely to be per app.

Amazon Kinesis Agent needs custom checkpoints file location

---

roles/aws-kinesis-agent/files/configure-aws-kinesis-agent

Current behaviour of cloud-watch-logs agent and no reason to change this.
See https://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html

MSS-542: Kinesis Agent initialPosition: START_OF_FILE

---

roles/teamcity-agent/tasks/main.yml

We tried to write integration tests that launch Elasticsearch in docker containers but hit the following error:
```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
This update [follows the Elasticsearch guidance](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) and increases the limit on the hosts.
We have verified manually on a single agent that this fix works. Does anyone know how I can launch a CODE AMIgo agent to test it in reality?

Increase mmap limit for launching Elasticsearch docker containers

---

roles/node/tasks/main.yml

#225 missed a check that broke backwards compatibility with existing builds that simply specified `node_version`.

Fix bakes using `node_version`

---

roles/aws-await-tags/templates/await_tags.sh

@fredex42 found a problem where the `aws` CLI was not on the path at start-up, causing the script to fail and no user data scripts to run.
This PR hard-codes the absolute path to avoid the problem.

Hard-code path to cli in aws-await-tags

---

roles/airflow/defaults/main.yml

This bake has been failing for a while, see [here](https://amigo.gutools.co.uk/recipes/datatech-airflow/bakes/62).
By adding this dependency, `pg_config` is available to execute the airflow installation.

Ensure that Airflow has pg_config binary available for install.

---

app/components/AppComponents.scala

There is some evidence that the AMI deletion stuff has gone rogue. We're disabling it for now.

Disable scheduler to prevent accidental AMI deletion

---

app/housekeeping/BakeDeletion.scala
app/housekeeping/MarkOldUnusedBakesForDeletion.scala
app/housekeeping/MarkOrphanedBakesForDeletion.scala
app/prism/Prism.scala
app/services/PrismAgents.scala

A smaller more comprehensible alternative to #304 in response to @adamnfish fair criticism of the half-hearted adoption of `Attempt`.
AMIgo has been deleting AMIs that were in use due to a race condition at startup. If AMIgo runs a housekeeping job before it has managed to populate data from Prism it will think that no AMIs are in use as the instance and launch config lists will be empty. This is not good™️.
This PR:
- changes the initial state of the prism caches from `[]` to `Left(NotInitialised)`
- never sets the data cache back to `[]` when it can't parse the prism response
- will not use stale data from prism
- internally flags prism data as stale when we've not successfully updated in 15 minutes

Fix initialisation race condition by dealing with empty prism cache

---

app/components/AppComponents.scala

Reverts guardian/amigo#300 following remediation work in https://github.com/guardian/amigo/pull/305

Revert "Disable scheduler to prevent accidental AMI deletion"

---

app/housekeeping/TimeOutLongRunningBakes.scala
test/housekeeping/TimeOutLongRunningBakesSpec.scala

Following up from the DevX chat...
If a bake has run for over an hour, but we can't find the associated EC2 instance, still update the status of the bake to TimedOut. This is to handle cases where e.g. the EC2 instance was deleted manually.

bake timeout - handle case when EC2 instance not found

---

app/packer/PackerBuildConfigGenerator.scala

Reverts guardian/amigo#317
It still failed on t2.micro so very unlikely to be this. Let's leave it back on t3 for the cost / performance benefits.

Revert "Revert to t2.micro"

---

app/housekeeping/TimeOutLongRunningBakes.scala
app/packer/PackerBuildConfigGenerator.scala

An EC2 instance for a given bake couldn't be found, since different formats of a bake id were used for tagging and searching for an instance respectively. 
This PR fixes the issue by using the same bake id format for tagging and searching.
Agreed with @philmcmahon that centralising tagging logic for now is overkill.

consistent formatting of bake id for tagging and searching of EC2 instances

---

README.md
roles/docker/tasks/main.yml
roles/pip/tasks/main.yml
roles/teamcity-agent/meta/main.yml
roles/teamcity-agent/tasks/sbt.yml

Bakes are having memory problems when trying to run `sbt sbtVersion` because it's trying to allocate ~750mb memory
```
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["sbt", "sbtVersion"], "delta": "0:00:00.401031", "end": "2019-06-12 15:53:48.685987", "msg": "non-zero return code", "rc": 1, "start": "2019-06-12 15:53:48.284956", "stderr": "OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d5550000, 715849728, 0) failed; error='Cannot allocate memory' (errno=12)", "stderr_lines": ["OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d5550000, 715849728, 0) failed; error='Cannot allocate memory' (errno=12)"], "stdout": "#
```
This PR should fix that by allocating more memory to SBT. It also modifies the docker version number of the teamcity agent …

Bump SBT memory for teamcity agent role. Bump docker version 

---

app/models/BaseImage.scala

Right now all recipes that use [ubuntu-bionic (18.04)](https://amigo.gutools.co.uk/base-images/ubuntu-bionic%20(18.04%20LTS)) are failing. This seems to be caused by a bug somewhere in the os that causes the ansible installation to hang forever (presumably waiting for user input):
```
...
[2019-06-25 07:00:48] bionic-java8: + apt-get --yes install ansible
[2019-06-25 07:00:48] bionic-java8: Reading package lists...
[2019-06-25 07:00:48] bionic-java8: Building dependency tree...
[2019-06-25 07:00:48] bionic-java8: Reading state information...
[2019-06-25 07:00:48] bionic-java8: The following additional packages will be installed:
[2019-06-25 07:00:48] bionic-java8: libpython-stdlib libpython2.7-minimal libpython2.7-stdlib 
... [ some stuff removed here]
[2019-06-25 07:00:52] bionic-java8: …
```

workaround for bug in ubuntu-bionic

---

roles/airflow/README.md
roles/airflow/templates/etc/airflow/airflow.cfg.j2
roles/airflow/templates/usr/local/bin/airflow-update-connections.sh.j2
roles/airflow/templates/usr/local/bin/airflow-update-dags.sh.j2

Currently the paths to connections, logs, plugins and dags are set in role params in Amigo. Doing it this way forces us to hard code `PROD` parameters in the recipe.
By reading them from env variables we can set them in our launch configuration and set them to different paths depending on whether it is a `CODE` or `PROD` stack.
This PR should be merged after the [PR](https://github.com/guardian/amigo/pull/321) that fixes the Ubuntu Bionic base image

Enable Airflow paths to be set in the  launch configuration

---

roles/airflow/tasks/install.yml

Flask 1.1.0 released on Jul 5 doesn't seem to work with our airflow setup. It successfully bakes an image but it fails to start airflow. [release history](https://pypi.org/project/Flask/#history)
This PR fixes the flask version to 1.0.4 released a day earlier that is the latest one that works for us.
Hopefully we can fix this in a better way in the future

workaround for latest version of flask breaking airflow

---

roles/airflow/templates/lib/systemd/system/airflow-mutex.service.j2
roles/airflow/templates/usr/local/sbin/airflow-scheduler-mutex.sh.j2
roles/airflow/templates/usr/local/sbin/autoscaling-ensure-one-instance.sh.j2

the service that prevents more than one airflow to run within the same asg always checks prod instead of the proper stage.
Tested in `CODE`

remove hardcoded PROD in airflow mutex service

---

roles/docker-compose/README.md
roles/docker-compose/tasks/main.yml

It's a role that installs Docker Compose. Very exciting.
You can specify `version`. If you don't you get the latest. Scintillating.
The Teamcity Agent role already does this, [pinned to a particular version](https://github.com/guardian/amigo/blob/7fef5db5851a3fa69eba0734e21c5c5a1f7f9db1/roles/teamcity-agent/tasks/main.yml#L25). Could be nice to modify it to use this in the recipe?

Docker compose

---

roles/airflow/templates/lib/systemd/system/airflow-connections-update.service.j2
roles/airflow/templates/lib/systemd/system/airflow-scheduler.service.j2

The update connections service was configured to start after the airflow scheduler. This meant that sometimes airflow tasks failed as they were scheduled to run before the required connections were available.
This PR reverses the dependency so that the scheduler will only start once all the connections are added
I tested it baking a `CODE` image and deployed it to `CODE` Airflow
According to the logs it seems to work well :
```
Jul 24 15:09:34 ip-10-248-183-223 systemd[1]: Starting Airflow connections update...
-- [A bunch of lines adding the connections here ] ----------------
Jul 24 15:12:20 ip-10-248-183-223 airflow[3786]: [2019-07-24 15:12:20,292] {jobs.py:1500} INFO - Starting the scheduler
```
I have not actually run any real EMR jobs though,  not sure if we need to do some more in …

Ensure all connections are updated before starting airflow scheduler

---

roles/docker-compose/tasks/main.yml

Follow up to #325 to use the correct syntax to differentiate between installing the latest and a given version.
NB: needs testing locally or in CODE before merging

Fix Docker Compose install latest

---

roles/airflow/defaults/main.yml

Disable the  airflow [experimental REST API](https://airflow.apache.org/api.html) 
relate
related github issue here: https://github.com/guardian/ophan-data-lake/issues/4242
Tested in `CODE`

disable airflow REST API

---

app/packer/PackerBuildConfigGenerator.scala

Installing the `logstash-input-kinesis` plugin is failing on a `t3.micro` for... some reason...
Tested and proved this change on CODE.

bump instance type to t3.small

---

roles/airflow/defaults/main.yml

Previously, when a new user signs in to Airflow via Oauth, they are automatically given Admin access. We want to restrict permissions for users outside of datatech so this will ensure that new users have the more restricted User role.
I have also been through and changed users from other teams to have the User role. Unfortunately, Thomas and I were unable to find a way to overwrite the default permissions for different roles. Rather than creating new roles, we are just using the default ones for now.

Airflow: change default user registration role

---

roles/teamcity-agent/files/awsconfig_cleanup.sh
roles/teamcity-agent/tasks/main.yml

adding cleanup script for phantom ".aws" directories left behind owned by root.
These have been present regularly on TC build agents and are breaking builds that rely on pulling a Docker image from ECR @philmcmahon @AWare

AWS config cleanup

---

roles/airflow/defaults/main.yml
roles/airflow/tasks/install.yml

We are also removing the explicit flask dependency when installing airflow as we don't believe that this is necessary anymore.
There are a number of other dependencies that are included in the bake, which I'd question - e.g. `numpy` - but I'm not planning on doing a full audit of airflow's requirements today.

Bump the version of airflow to the latest stable version 1.10.5.

---

roles/airflow/templates/etc/airflow/airflow.cfg.j2

This fixes Airflow configuration deprecation warnings.
More info on Trello: https://trello.com/c/2ieGKdNF/260-fix-airflow-warnings

Fixed deprecated Airflow config keys for Elasticsearch

---

roles/cloudwatch-hardware-monitoring-cronjob/README.md
roles/cloudwatch-hardware-monitoring-cronjob/defaults/main.yml
roles/cloudwatch-hardware-monitoring-cronjob/tasks/main.yml

Issues:
- `when` indentation meant that condition wasn't used and therefore facts were always set (therefore, all command line options always provided)
- logic to join paths meant that first path in array would not be prefixed with `--disk-path` (which is why providing `--disk-path` explicitly works [here](https://amigo.gutools.co.uk/recipes/centralised-elk-lk))
When this is merged I will update the roles which depend on this recipe accordingly.

fix bugs in cloudwatch-hardware-monitoring-cronjob role

---

roles/ruby-gems/README.md
roles/ruby-gems/meta/main.yml
roles/ruby-gems/tasks/main.yml

A few teams (iOS, Android, Editions) are now using [`fastlane`](https://docs.fastlane.tools/) for app distribution, so we'd like to include it on the TeamCity build agents.
Fastlane is [installed as a gem](https://docs.fastlane.tools/getting-started/android/setup/#installing-fastlane), so this PR adds a new role for installing ruby gems (thanks to @philmcmahon for the suggestion to add a more generic role for this purpose).
I've tested this locally using the instructions here: https://github.com/guardian/amigo#testing-ansible-scripts-without-runing-amigopacker

Add role for installing ruby gems

---

roles/airflow/tasks/install.yml

This is to fix compatibility issues between `pandas-gbq` installed by `apache-airflow[gcp]` and importing the latest `requests-oauthlib` and `oauthlib>=3.0.0` while airflow's `flask_appbuilder` requires `requests-oauthlib==0.8.0` and `oauthlib==2.0.6`.
Compatible version taken from: https://github.com/lepture/flask-oauthlib/blob/v0.9.5/requirements.txt

Override requests-oauthlib and oauthlib versions

---

roles/cloudwatch-hardware-monitoring-cronjob/defaults/main.yml
roles/cloudwatch-hardware-monitoring-cronjob/tasks/main.yml

Update cloudwatch-hardware-monitoring-cronjob so that memory used and disk space used can be collected.

Allow for more instance metrics to be collected

---

roles/airflow/tasks/install.yml

A very similar problem as in the one here https://github.com/guardian/amigo/pull/323
The Werkzeug library released a new version that broke our Airflow setup, bakes work but Airflow deployments fail.
This PR pins the library to the working version we had in the previous bakes to unblock Airflow deployments.
We can evaluate later if upgrading to the latest version of Airflow fixes this as a long term solution.
Deployed to Amigo `CODE` and deployed Airflow `CODE` successfully using that AMI.

Quick fix for Airflow recipe

---

.gitignore
roles/aws-cloud-watch-agent/README.md
roles/aws-cloud-watch-agent/tasks/main.yml

Some of the functionality this brings is already provided by other Amigo roles, however, this is the canonical approach suggested by AWS for EC2 instance metric collection; allows for more configuration; and enables the collection of SDK metrics (c.f. the work I'm about to do - will report back when I've learnt more).
Tested, locally and on CODE.

Add role for new cloud watch agent

---

roles/docker/tasks/main.yml

When Ansible 2.9 was [released](https://docs.ansible.com/ansible/latest/roadmap/ROADMAP_2_9.html) on 31 October 2019, it [removed the option](https://github.com/ansible/ansible/issues/47869) to set the apt package state as `installed`.
The equivalent option is now called [`present`](https://docs.ansible.com/ansible/latest/modules/apt_module.html#parameter-state
).
This has caused [Amigo bakes to fail](https://amigo.gutools.co.uk/recipes/teamcity-agent) since November 2019, with the message:
```
[2020-02-17 01:07:02] teamcity-agent: failed: [127.0.0.1] (item=[u'apt-transport-https', u'ca-certificates', u'openssl']) => {"ansible_loop_var": "item", "changed": false, "item": ["apt-transport-https", "ca-certificates", "openssl"], "msg": "value of state must be one of: absent, build-dep, fixed, …
```

Fix Docker task, removing 'state: installed'

---

roles/aws-rds-root-cert-ca/defaults/main.yml
roles/aws-rds-root-cert-ca/meta/main.yml
roles/aws-rds-root-cert-ca/readme.md
roles/aws-rds-root-cert-ca/tasks/main.yml
roles/aws-rds-root-cert-ca/vars/main.yml

For anyone interested in using full on SSL when connecting to an RDS service. This role gets the certificate, adds it to a new truststore & imports the default Java truststore certificates into that one.

Role: RDS Root CA Certificates

---

roles/airflow/defaults/main.yml
roles/airflow/tasks/system.yml
roles/airflow/templates/lib/systemd/system/airflow-initdb.service.j2
roles/airflow/templates/lib/systemd/system/airflow-install-ophan-python.service.j2
roles/airflow/templates/usr/local/bin/airflow-install-ophan-python.sh.j2

Add a new service to Airflow to download and install the Python directory published by the new Riff Raff generated instance.

Mt add service to install airflow python

---

roles/airflow/templates/lib/systemd/system/airflow-connections-update.service.j2
roles/airflow/templates/lib/systemd/system/airflow-initdb.service.j2
roles/airflow/templates/lib/systemd/system/airflow-install-ophan-python.service.j2
roles/airflow/templates/lib/systemd/system/airflow-scheduler.service.j2
roles/airflow/templates/lib/systemd/system/airflow-webserver.service.j2

The systemd services are wired strangely, without enforcing some required order.
After boot, the webserver.service keeps trying to start despite the design generally
requiring initdb and other things. This simpler mapping allows the design to inject the
ophan python installation as a requirement of initdb which will continue to be useful.

Simplify Requires / Bind & After services configs

---

roles/airflow/templates/lib/systemd/system/airflow-webserver.service.j2

The webserver sevice is needed for RiffRaff to receive a 200 from the health check port. Making it dependent on the mutex means that there is nothing listening to that port on the new  instance during its deployment (because there will always be 2 services).
So RiffRaff thinks it isn't healthy and won't kill the old node.
In the future we will move the mutex into a subdirectory airflow-scheulder.requires or similar. But that is not a simple change in current architecture.

Remove webserver dependency mutex

---

cloudformation.yaml

This will allow us to close port 22 access entirely. This is already released on CODE and PROD.
See https://github.com/guardian/ssm-scala/pull/111 for details

Add extra permissions required for SSM-tunnel.

---

roles/airflow/templates/etc/sysconfig/airflow-environment-file.j2

Allow `from dags.<dagfile> import dag` on deployments. This is the value used as the PYTHONPATH when the daemons for the airflow components. Prepending it just makes airflow home available which is just a useful convention.
This file is created at BAKE... values from deployment and secrets are appended on deployment by cloudformation step. It is the EnvironmentFile. All good.
This PYTHONPATH setting means that AIRFLOW_HOME isn't known to the
PYTHON executable when it is invoked by the systemd services that manage
the webserver, executor and scheduler. That is because in the BAKE this
file is  unpacked into /etc/sysconfig/ which is then used for the
Environment File.
Just adding a second value means that we can use conventions in Airflow
development that import from the path. Such as …

Prepend AIRFLOW_HOME to PYTHONPATH

---

roles/teamcity-agent/tasks/main.yml

I'm currently trying to get the editions android build to run on ubuntu agents in teamcity. The current error I'm facing is 'ENOSPC: System limit for number of file watchers reached'. This applies both to builds directly on the machine as well as to those run in a docker container.
This change bumps the limit for max_user_watchers, making use of the built in ansible sysctl command (we already do this for max_map_count). I've tested this change directly on an agent by sshing in to verify that it solved my build problems.

Teamcity agent role: bump max_user_watchers

---

roles/airflow/files/patches/AIRFLOW-1916-dont-duplicate-logs.diff
roles/airflow/tasks/install.yml

Airflow logging to remote locations (such as S3) duplicates logs on each write where there is both a remote and a local copy of the logs at the point of opening. The compounding factor is that this hits UP_FOR_RESCHEDULE models the hardest, and we have lots of long running sensors with UP_FOR_RESCHEDULE.
This patch essentially clears the logging file, before writing to it. Thus no duplication!
While here add a `files/` dir to the module. This allows the
subdirectories to be called in the ansible patch module itself because
it will search relative to this path.
Actual patch:
Taken from: https://github.com/apache/airflow/pull/7120
Related to: https://issues.apache.org/jira/browse/AIRFLOW-6522

Patch Airflow Logging Fix into VirtualEnv Installation

---

roles/airflow/tasks/install.yml

Overnight WTForms release 2.3.0 which introduces a breaking  change for Airflow. Pin the version until resolved in the dependencies.

Pin WTForms to 2.2.0 in Airflow Role

---

roles/disk-available-cronjob/tasks/main.yml

This was causing `grid-imaging` and `grid-imaging-eoan` to fail.
@aug24 @philmcmahon

Fix quoting on string in disk available

---

roles/ebs-volume/README.md
roles/ebs-volume/files/attach-ebs-volume.sh
roles/ebs-volume/tasks/main.yml

With Amazon nitro, EBS volumes are made available at paths like `/dev/nvme0n1`. 
There's no strict dependency between what the device is and it's path. 
They have turned out to mostly be deterministic, however the new Ubuntu version changes that. 
This uses the script from @mbarton  and @joelochlann to find the correct device path from the supposed device path that is set in the EBS. I've taken the liberty of ripping out half the script and adding the UUID to the fstab per amazons documentation. 
*TODO*

safely mount ebs volumes

---

app/models/BaseImage.scala
roles/docker-ecr/README.md
roles/docker-ecr/files/config.json
roles/docker-ecr/tasks/main.yml
roles/docker/README.md

*Note: have successfully built an Amazon Linux 2 AMI with the `docker-ecr` role on Amigo CODE and then tested that in the Frontend AWS account.*
We use multiple languages and the surrounding tooling (cloudformation, AMIs, riffraff bundling, etc.) is language-specific. This means a lot of repetition. Docker provides a standard interface here.
Amazon Linux 2 has been used as the base image for a few reasons, but primarily because it has good out-of-the-box support for Docker (with the `amazon-linux-extras` package).
Re-use of deployment code across languages/projects.
`UserData` in cloudformation runs as `root`, but I've added the credentials helper config to the `ec2-user` home, which means it will only be found when launching a docker command with the ec2-user user.
What do people think …

Docker credentials and Amazon Linux 2 base image

---

roles/metricbeat/README.md
roles/metricbeat/tasks/main.yml

Add role for [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-getting-started.html) to allow the collection of [elasticsearch metrics](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html).
Initially, this will be used to collect metrics about the Central ELK stack. We can look at expanding it for use by [Ophan](https://github.com/guardian/ophan/issues/3898).
Bake an image using this role? This has been done successfully on CODE.
An AMI can be baked with metricbeat installed.
n/a
n/a

Add metricbeat role

---

app/views/showRecipe.scala.html

Easiest to review w/out whitespace https://github.com/guardian/amigo/pull/378/files?w=1.
Deep-link into AMIable. This view in AMIable provides information about the AMI, including:
- creation date
- ARN
- any launch configurations that use it
- any instances that use it
- any available updates
This is useful to double check if we have setup a stack's auto-update correctly: if we see the most recent AMI not used, but an AMI from last month is, then we've likely misconfigured the app in RiffRaff.
NOTE: Although there is a CODE stack for AMIgo, there is only a PROD stack for AMIable.
This also makes the structure of the `table` a bit simpler with a dedicated column for the copy button and the new AMIable link, whereas before the copy button was part of the ami id column.
- …

Add a link to view the AMI in AMIable.

---

app/views/showRecipe.scala.html

For the encrypted copy row, use the correct AMI ID when crafting the link to AMIable. Previously this was using the AMI ID from the vanilla bake, which is incorrect.
Related to https://github.com/guardian/amigo/pull/378.
- Observe the correct AMI ID is used when clicking on the AMIable link
Link destination is correct.
n/a

use the correct AMI ID

---

roles/puppeteer/tasks/main.yml

Time machine stopped working on Monday 14 September due to the wrong version of libxss1. This PR adds the libxss1 dependency to this AMI, used only by ophan-time-machine. 
See further details here: https://github.com/guardian/ophan/issues/3932

Add libxss1 dependency to fix time-machine

---

app/views/showRecipe.scala.html

Following from https://github.com/guardian/amigo/pull/383.
Remove the `+`s from the URL. `+` is what Chrome appears to encode ` ` to in the URL bar. As we're running `+` through `helper.urlEncode`, the `+` is ending up as `%2B` which is totally incorrect.
Replacing it with ` ` results in `%20`, which is correct.
Not entirely sure how I missed this, maybe the browser cached something?

Correct URL to GitHub search

---

roles/teamcity-agent/tasks/main.yml

This configures the docker daemon to pull via nexus rather than straight from docker hub. This is to avoid failures due docker hub rate limiting.
A new spot instance that runs a teamcity build that triggers a docker pull should have an effect on nexus. Docker images should start to be cached at https://nexus.gutools.co.uk/#browse/browse:docker
N/A
If this is misconfigured, docker pulls will fail. So every teamcity build that relies on it will grind to a halt.

Make docker pull via nexus.gutools

---

roles/teamcity-agent/tasks/main.yml

Uses [Ansible's known_hosts module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/known_hosts_module.html) to add GitHub's public key into `/etc/ssh/ssh_known_hosts` on the TeamCity agents.
Used in conjunction with [TeamCity's SSH Agent build feature](https://www.jetbrains.com/help/teamcity/ssh-agent.html), this is a more idiomatic solution than #390. It does, however, require us to upload an SSH key to TeamCity via the UI; this action won't be stored in VCS.
This will allow a project to reach GitHub during a build.
**Okay... but we can already reach GitHub...?**
Yes. Correct. We can reach GitHub at the point of fetch/checkout, not at the point of _build_. The key used for fetch/checkout is removed once that step has completed regardless of the checkout mode:
From …

Add github.com to ssh_known_hosts

---

roles/wazuh-agent/meta/main.yml
roles/wazuh-agent/tasks/main.yml

This adds a new role called wazuh-agent. It installs the `wazuh-agent` package and patches its systemd unit so it calls `authenticate-with-wazuh-manager.sh` _before_ the actual agent runs.
`authenticate-with-wazuh-manager.sh` patches wazuh-agent's config file so it connects properly, and registers the box using `agent-auth`
The role is parameterised and requires a number of variables to run, namely
* manager_ip
* agent_version
* secret_arn
For reference: bash version https://github.com/guardian/amigo/blob/f8c1745bd4ee96172dd26a11a3665324e0a2cd69/roles/wazuh-agent/tasks/main.yml
systemd is the way modern ubuntu manages services. Each service has an associated text file that describes its implementation according to systemd's interface. These include properties like what commands do you run …

Add Wazuh Agent role

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/models/BakeLog.scala
app/packer/PackerBuildConfigGenerator.scala
app/packer/PackerRunner.scala
app/schedule/ScheduledBakeRunner.scala
app/services/AmiMetadataLookup.scala

Wth the advent of [Graviton](https://aws.amazon.com/ec2/graviton/) AWS instances we need to update our tooling to build AMIs that can be run on the ARM architecture. This PR detects the architecture of the base AMI and uses an appropriate instance to bake the AMI.
You can now create a recipe that uses an ARM base AMI. When you do so you will notice that packer will create an instance using a `t4g.small` type rather than a `t3.small` type.
Developers can experiment with using Graviton instance types.

Detect architecture when baking

---

roles/aws-tools/tasks/install-cfn-tools-Ubuntu-post-focal.yml
roles/cloud-watch-monitoring/tasks/main.yml
roles/docker/tasks/main.yml
roles/exiftool/tasks/main.yml
roles/golang/tasks/main.yml
roles/graphicsmagick/tasks/main.yml
roles/install-ruby/tasks/main.yml
roles/java8/tasks/main.yml
roles/kong/tasks/main.yml
roles/nginx+pagespeed/tasks/main.yml
roles/nginx-extras/tasks/main.yml
roles/perl-useful-packages/tasks/main.yml
roles/pngquant/tasks/main.yml
roles/useful-packages/tasks/main.yml

I noticed some deprecation warnings and decided to fix them as that's better than it breaking when ansible 2.11 appears on our instances.
This should have no impact - all bakes should continue to work as expected.

Migrate deprecated uses of ansible's apt task

---

roles/wazuh-agent/tasks/main.yml

This change makes the ansible step that fetches and stores wazuh's password fail if `aws secretsmanager get-secret-value` fails. Right now it doesn't fail because the aws command always has a return code of 0 - even when it fails!!
Luckily, ansible has a built in function to fail based on an error message, and in the examples I've seen there's always the word "error" in the error message.
```
* An error occurred (AccessDeniedException) when calling the GetSecretValue operation:
* aws: error: argument --region: expected one argument
```
Trying to bake `wazuh-agent-test` in amigo code should fail, and it does! https://amigo.code.dev-gutools.co.uk/recipes/wazuh-agent-test/bakes/48

Make wazuh agent bake fail on aws error

---

roles/pip-packages/README.md
roles/pip/README.md
roles/pip/tasks/main.yml
roles/pip3-packages/README.md
roles/pip3-packages/defaults/main.yml
roles/pip3-packages/meta/main.yml
roles/pip3-packages/tasks/main.yml
roles/pip3/README.md
roles/pip3/meta/main.yml
roles/pip3/tasks/main.yml

The package in Focal is `python3-pip` even though there's no Python 2 in that release. Before this PR, the `pip-packages` role didn't work on that release as it hard-codes a dependency on `python-pip`.
This PR adds two new roles, `pip3` and `pip3-packages` that can be used on both Focal and Bionic to install Python 3 packages. As Python 2.7 is EOL we would expect users to migrate to using these roles and we can eventually remove the old ones. The naming however makes it clear which version of Python you are expecting to use, regardless of if the distribution packages 2.7 or not (thanks @AWare for the suggestion).
In fact, most of our AMIs already have Python 3 pip. We install it as as a dependency of [aws-tools](https://github.com/guardian/amigo/blob/a6323b56801b5880d683ff293bb74fb600595a6 …

Add pip3 role to support Ubuntu 20.04

---

app/controllers/BakeController.scala
app/controllers/RecipeController.scala
app/data/PackageList.scala
app/models/BakeId.scala
app/models/BaseImage.scala
app/models/RecipeId.scala
app/packer/PackerBuildConfigGenerator.scala
app/prism/RecipeUsage.scala
conf/routes
test/data/PackageListTest.scala
test/models/BakeIdTest.scala

This adds a /bakeUsages endpoint to list all the bakes in AMIgo that are currently in use. One use for this would be to fetch package lists for all bakes currently in use.
As part of this changed I've added some tests for the messty string manipulation bits of the package list work
I've tested this on CODE but it's not easy to test locally or on CODE as no locally or CODE baked images are 'in use' so you might have  to take my word for it
The endpoint works, and gets used at some point.

Add endpoint to list bake usages

---

app/controllers/BaseImageController.scala
app/controllers/RecipeController.scala

There is currently no check on whether an ID for a new (or cloned) base image or recipe has characters in it. The quickest solution is to add a minlength to the form.
Try to create or clone a recipe with no name.
Better errors than a unknown exception explosion.

Add some min lengths for IDs

---

app/components/AppComponents.scala
app/models/packer/PackerBuilderConfig.scala
app/packer/PackerBuildConfigGenerator.scala
app/packer/PackerConfig.scala
cloudformation.yaml

Security HQ was showing an error when trying to collect the security groups of the Deploy Tools account. After debugging, we learnt that AWS Trusted Advisor was unable to return a response for an account with over 200 security groups. The Deploy Tools account had over 850! Most of these were temporary Packer security groups created by Amigo. Whilst we wrote a script to delete the unused security groups, we wanted to find a way to stop Amigo creating all of these security groups.
We decided to add SSM support to Packer and create two dedicated security groups (one for CODE and another for PROD), so that the security groups do not need any inbound access rules and also so that we no longer create a new temporary security group for each new Packer instance created by Amigo.
> Support for the …

Adds SSM capability to Packer

---

roles/node/defaults/main.yml
roles/node/tasks/main.yml

In order to support both x64 and amr64 architectures for amigo bakes it makes senst to parameterise the architecture in this role. Ideally we'd calculate this based off the architecture of the instance packer is running on, but this is a fairly quick fix in the short term.
**Testing**
This has been tested on CODE https://amigo.code.dev-gutools.co.uk/recipes/devx-arm64-test.
I've also verified that recipes where 'architecture' isn't specified still work

Parameterise architecture for node role.

---

roles/ssh-reserve-disk-space/README.md
roles/ssh-reserve-disk-space/tasks/main.yml

On many occasions teams have been unable to SSH to instances using SSM because the instance has run out of disk space.  This adds a role which reserves 10MB of diskspace for `/home/ubuntu/.ssh` which should avoid this issue.
Based on https://docs.google.com/document/d/1IvLH8jt5JNYWwsr8S2mDEISVtSDwCnjBMfSmmYun_FI/edit

Add role to reserve disk space for .ssh directory

---

app/models/BaseImage.scala

This changes the tool used to generate the package list on Ubuntu bakes from `apt list` to `dpkg-query`. The motivation here is mainly to generate a file in a format that can be scanned for vulnerabilities using https://github.com/canonical/sec-cvescan but the package list generated is also a bit less verbose which is perhaps a good thing 
Run a bake, observe changes to the package list (see below for examples)
If the package list continues to be generated and, longer term, we can try scanning package lists with sec-cvescan then happy days.
There will be an awkward period whilst the package lists are being switched from the apt list to the dpkg format which will mess up the diff introduced in https://github.com/guardian/amigo/pull/535 but since that feature is brand new this shouldn't …

Use dpkg-query instead of apt list to generate package list

---

cloudformation.yaml
roles/wazuh-agent/tasks/main.yml

This refactors the wazuh agent registration script to fetch tags from the instance's autoscaling group instead of its own tags via `ec2 describe-tags`. Because the script runs on boot, it might be that it queries for tags before they've assigned to the instance. Fetching them from the ASG avoids this issue altogether.
I've that it builds in amigo code. I haven't been able to launch the ami in a test instance, as it requires that instance to be in an ASG. I've ran the script in the amiable CODE instance by SSHing though.
I think this needs to be merged and then each service migrated and checked one by one.
The big risk is that the instances don't have permissions to run `describe-auto-scaling-instances` and `describe-auto-scaling-groups` and the whole things bombs. Shouldn't affect the …

Query for ASG tags instead of instance tags

---

roles/aws-kinesis-agent/tasks/main.yml

Which supports ARM.
The earlier version has a SQLite dependency that breaks on ARM instances

Upgrade aws-kinesis-agent to 2.0.1

---

app/controllers/BakeController.scala
app/data/Bakes.scala
app/data/PackageList.scala
app/views/fragments/bakeOutput.scala.html
app/views/showBake.scala.html
build.sbt
public/stylesheets/main.css

This change makes use of google's [diff-match-patch](https://github.com/google/diff-match-patch) library to generate a diff of the package lists of the current bake and the previous bake. This results in a more useful indication of what changed in the current bake.
Perform at least 2 bakes on a recipe with some change between them. You should see the diff show up on the bake page. Locally you can experiment with [this recipe](http://localhost:9000/recipes/node-is-theft/bakes/3)
Next time someone has an issue they suspect is caused by a change in an AMI it should be more obvious to them what has changed.

Show a diff of modified packages between bakes

---

cloudformation.yaml

Allows AMIgo to terminate ssm sessions. I've noticed some (but strangely not all) bakes failing because amigo can't terminate the ssm session, e.g. https://amigo.gutools.co.uk/recipes/centralised-elk-es/bakes/184. This change solves the problem by giving amigo the permision to do this.
[This bake](https://amigo.gutools.co.uk/recipes/centralised-elk-es/bakes/184) is consistently failing right now, after this change it should work.

Allow amigo to terminate ssm sessions.

---

roles/wazuh-agent/tasks/main.yml

Modifies the wazuh agent bootstrap script to include the app, stack and stage tags as part of the instance. The motivation for this is that wazuh doesn't include labels in the main agent list, so you just get a wall of instance ids which are kinda hard for the average brain to parse. The new format is app-stack-stage-instanceId - the idea being that unless we're doing a search for a specific instance the instance ID is the least useful piece of info.
I've performed a test bake on CODE but the real test will be using the new script in an AMI that is actually used by an app that reports to wazuh. Testinig this all out on CODE would be pretty time consuming so I propose just merging to prod then immediately running a bake for [this AMI](https://amigo.gutools.co.uk/recipes/arm64-bionic-java8-d …

Wazuh: Inclue app,stack,stage tags in agent name

---

roles/ansible-facts/README.md
roles/ansible-facts/tasks/main.yml

\* worked on with @Fweddi 
Adds a role to facilitate the discovery of Ansible facts. This role helped us extend the `aws-cloudwatch-agent` role (#540) to ARM64 architecture. See example in README in PR for more details.

Ansible facts role

---

roles/aws-cloud-watch-agent/README.md
roles/aws-cloud-watch-agent/tasks/main.yml

\* worked on with @Fweddi 
Update the `aws-cloudwatch-agent` role to dynamically install the `amazon-cloudwatch-agent.deb` dynamically based on the architecture (architectures supported: amd64, arm64).
Uses the Ansible fact `ansible_architecture` to determine the architecture.
Tested on CODE by:
1. creating a new base image `ARM ubuntu-xenial` (as was done on PROD)
2. cloning the recipe `ubuntu-xenial-capi` (clone name: `ubuntu-xenial-capi-ARM`) and changing the base image to `ARM ubuntu-xenial`
3. baking recipes [`ubuntu-xenial-capi`](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi/bakes/2) and [`ubuntu-xenial-capi-ARM`](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi-ARM/bakes/1) and eyeballing the logs to check the appropriate package was installed

Update aws-cloudwatch-agent role to support ARM64 architecture

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/packer/PackerRunner.scala
app/schedule/ScheduledBakeRunner.scala

This implements a brutally simple limiter to cap the number of bakes running at once. It seems that AMIgo can become overwhelmed when a large number of scheduled bakes kick off and this should limit the impact of that.
Deploy to CODE and try to kick off more than five bakes. Anything over five should not start until prior bakes have completed.
We have fewer scheduled bake failures.

Add concurrent bake limit

---

roles/friendly-hostnames/files/set-hostname.sh

In the past 2 days, the Ophan team have seen this error from the friendly-hostnames role:
```
An error occurred (InvalidInstanceID.NotFound) when calling the CreateTags operation: The instance ID 'i-059607dad87f615d7' does not exist
```
We are quite surprised that this is happening, since we had assumed that the aws-await-tags step would ensure that the EC2 API was ready, but it seems like the [apis eventual consistency](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency) isn't as straightforward as that.
Rather than spend too much more time investigating what the rules are of the AWS API, I've added retry logic to the friendly-hostnames role.  This is copied from the aws-await-tags role.

Add retry logic to friendly-hostnames role

---

roles/logstash-deb/tasks/main.yml

* worked on with @Mullefa 
Update the logstash-deb role to dynamically install the logstash.deb based on the architecture and version of logstash (architectures supported: amd64, arm64).
Uses the Ansible fact ansible_architecture to determine the architecture. 
Installs for logstash < v7.10.0 are not supported for ARM architecture, so we fail the build. For v7.10.0 and above, we install either the ARM or AMD variant of logstash depending on ansible_architecture.
Test bakes:
* [AMD64 pre-7.10](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi/bakes/3)
* [AMD64 post-7.10](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi/bakes/4)
* [ARM64 pre-7.10](https://amigo.code.dev-gutools.co.uk/recipes/ubuntu-xenial-capi-ARM/bakes/6)
* [ARM64 …

Update logstash-deb role to support ARM64 architecture for logstash versions >= 7.10.0 (fail if < 7.10.0)

---

roles/java11/meta/main.yml
roles/java11/spec/java11_spec.rb
roles/java11/tasks/main.yml

JRE11 has been supported by Scala for [some time now](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#version-compatibility-table) and has some [key optimisations for ARM64 machines](https://bugs.openjdk.java.net/browse/JDK-8189104).
This adds a role that should be a simple swap out for recipes switching from version 8.
This impacts baked AMIs so best tested by converting an AMI over.

Add JDK 11 as a role

---

roles/kong/defaults/main.yml
roles/kong/tasks/main.yml

Updates Kong role to assume an ubuntu 18.04 base image rather than 16.04.
Provoked by the AWS CLI Python 3.6 fail this week but also gets us ready for the 16.04 end of support.
Levels the postgres client from 9.5 to the 10 provided in bionic (this is safe because it's only used for ad hoc queries).
Baked by deploying this branch to CODE.
Deployed the AMI to CODE Kong.
Checked access logs and logstashing.
No used facing impact should be visible.
Wierd Kong / Perl errors.
Should be safe as Kong provide a specific bionic .deb package.

Move Kong base image to bionic LTS. Version postgres client to match

---

roles/aws-tools/tasks/install-pip-aws-cli-Debian.yml

This is the last version supported by Python 3.4/3.5, which aws has deprecated.
See deprecation warning https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-python-3-4-and-3-5-in-the-aws-sdk-for-python-and-aws-cli-v1/
> On February 1, 2021, the AWS SDK for Python (Boto3 and Botocore) and the AWS Command Line Interface (AWS CLI) v1 will no longer support Python 3.4 and Python 3.5. We encourage you to upgrade to Python 3.6 or later (this deprecation doesn’t affect customers using Python 2.7).
And the issue being reported on the awscli github project. Essentially the version of pip being used (v8) installs the awscli package even though it now depends on an rsa package version that doesn't run in Python 3.5 Charming
> [awscli v1.19.15 adjusted] our dependencies for rsa. …

Pin awscli to v1.19.12

---

cloudformation.yaml
riff-raff.yaml

Switches Amigo over to use AWS ARM64 Graviton instances, including:
- drop port 22 (nothing to do with this just hygeine)
- update sesssion manager/packer version
- Update recipe in riff-raff.yaml
Tested on CODE (with one succesful bake). To release to PROD:
- update stack via console and change the instance type to t4g.small
- merge this change and wait for CD to kick in.
Amigo still works and costs less to run

All aboard the Graviton train! 🚂 

---

app/housekeeping/MarkOldUnusedBakesForDeletion.scala
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala

Last month we experienced a problem launching new TeamCity agents, because [AMIgo had deleted the AMI associated with our TeamCity Cloud Profile](https://docs.google.com/document/d/1Qu5tPLMcAFzHx9Tzu3U_aAKHiEZkvdQKgpsGKrXpb9Y/edit).
In order to avoid a repeat of this problem, I was hoping to update the AMI associated with our Cloud Profile. Unfortunately the [bakes for this recipe](https://amigo.gutools.co.uk/recipes/teamcity-agent) have been failing for several weeks, so as things stand we run the risk of losing our only working AMI.
I'd like to prevent AMIgo from deleting `teamcity-agent` AMIs as a short-term measure so that we have time to debug and fix the failing bakes.
I've added a unit test to cover the new behaviour.
* Our [current `teamcity-agent` …

Prevent AMIgo housekeeping from removing TeamCity AMIs

---

roles/docker/tasks/main.yml

We no longer install `urllib3`, `pyOpenSSL`, `ndg-httpsclient` and `pyasn1` as part of the Docker role. The installation of these Python dependencies has been causing [recent bakes to fail](https://amigo.gutools.co.uk/recipes/teamcity-agent/bakes/148). More specifically, I think that the failure occurs because a transitive dependency for `ndg-httpsclient` [dropped support for Python 2.x recently](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#34---2021-02-07).
It wasn't clear to me why these packages were needed, so I tried removing them and everything still seems to work 🤷‍♂️ 
Testing done: 
1. Created a [copy](https://amigo.code.dev-gutools.co.uk/recipes/teamcity-agent-jw) of the [`teamcity-agent` recipe](https://amigo.gutools.co.uk/recipes/teamcity-agent) in `CODE`, which …

Stop installing python packages as part of Docker role

---

roles/java11corretto/README.md
roles/java11corretto/meta/main.yml
roles/java11corretto/spec/java11_spec.rb
roles/java11corretto/tasks/main.yml

This adds an alternative Java11 distribution (AWS's Corretto). The advantage of this distribution over OpenJDK is that AWS provide support if we have issues with it. This is of particular interest right now as we are having performance issues as we migrate applications onto ARM64.
I've tested that this role builds in CODE. If you install this then `java -version` should return a Corretto runtime.
Switching to use this might reduce CPU usage if it is better optimised for Graviton than OpenJDK. If it doesn't then we can raise a support ticket.
This distribution has better commercial support than the OpenJDK so the risks should be reduced.

Add AWS Java 11 (Corretto)

---

roles/node/README.md

The architecture param was introduced in https://github.com/guardian/amigo/pull/533 but not documented, so adding it here for future travelers.

update README for node role, to include 'architecture' param

---

roles/wazuh-agent/tasks/main.yml

This PR replaces `ec2metadata` calls with direct curl calls to the instance metadata service.
`ec2metadata` only works with IMDSv1, which some of our ec2 instances have blocked in favour of IMDSv2. Here's some detective work I did
* `ec2metadata` was originally a bash script published by amazon in `s3://ec2metadata/ec2-metadata` (really)
*  It was rewritten in python and made available for ubuntu distribution in the package `cloud-guest-utils`, which we install as part of the `useful-packages` recipe.
* Neither of these supports IMDSv2
* The ubuntu equivalent of a PR was opened in 2020 and it's been sitting there unmerged ever since https://bugs.launchpad.net/ubuntu/+source/cloud-utils/+bug/1882389
* According to the documentation we should be querying the service directly. Amazon seemed …

Replace ec2metadata with native calls

---

roles/docker/tasks/main.yml

This does what is says on the tin - sets up the docker role to install the correct version of docker-ce based off the current architecture.
How to test
========
Deploy to Amigo CODE, run the teamcity-agent recipe (or any recipe that uses docker): amigo.code.dev-gutools.co.uk/

Install arm64 version of docker when on arm64 architecture.

---

app/components/AppComponents.scala
app/controllers/BaseImageController.scala
app/data/BaseImages.scala
app/models/BaseImage.scala
app/views/baseImages.scala.html
app/views/editBaseImage.scala.html
app/views/fragments/eolStatus.scala.html
app/views/fragments/usagesColumn.scala.html
app/views/newBaseImage.scala.html
app/views/recipes.scala.html
app/views/showBaseImage.scala.html
app/views/showRecipe.scala.html
public/stylesheets/main.css
test/data/PackageListTest.scala
test/models/BakeIdTest.scala
test/models/BaseImageTest.scala

This PR aims to help prepare us for ubuntu Xenial being deprecated at the end of this month. It adds warning colours and labels next to Recipes and AMI's that are using a base image which is due to expire soon.
To make this work I've added a new property to the `BaseImage` case class and associated forms  - eolDate. Play Forms provides an adequate date picker for this purpose, it could be prettier but does  the job.
Most of the rest of the changes are to the views in order to expose this information. The CSS isn't super pretty (I copied it from riffraff) but given that our aim is to have zero images that are EOL soon I think it's probably fine to look a bit ugly.
Once this change is live we'll need to manually go through the existing base images and add an eolDate to them all. A link is …

Add end of life date to base images 

---

roles/teamcity-agent/files/teamcityagent.service

I'm trying to get teamcity to work on ubuntu bionic. Currently the bionic AMI starts up, registers with teamcity, realises it needs to upgrade then shuts down to prepare for the upgrade then gets stuck. This issue is discussed here https://stackoverflow.com/questions/12483230/teamcity-build-agent-wont-upgrade/25393243
This PR should solve this issue by adding exit code 143 as a success exit code. 
How to test
========
Merge this change, bake a new teamcity ami, add it to the cloud profile (there is a 'test teamcity' profile within the default one), spin up an agent and verify that it succesfully starts up.
Risks
====
None as far as I can think of, other than 143 turning out to be 'critical error please don't start me again' - which would be odd to use for that as well as for the upgrade …

Add exit code 143 as success exit code for teamcity agent

---

ansible/Vagrantfile
roles/fluentbit/README.md
roles/fluentbit/defaults/main.yml
roles/fluentbit/tasks/main.yml
roles/nginx-extras/README.md
roles/nginx-extras/tasks/main.yml

Introduces a `version` var for both roles to allow pinning.
Also some other minor tidyp (a README for the nginx-extras role as it should have one) and a fix for the Vagrant setup on Python versioning.

Support version pinning for nginx-extras and fluentbit roles

---

roles/wazuh-agent/tasks/main.yml

This makes the wazuh registration script try to fetch tags from the instance if the result from the ASG fetch is an empty string or the word "None". This will cover single instances, but ends up also covering if an instance only has permission to query its own tags and now its ASG ones.
Writing an if statement in bash is a known high risk situation. I've actually tested this code by running it
- In a single instance
- In an instance in an ASG without asg:describeTags, but with ec2:describeTags
- In an instance in an ASG with asg:describeTags
For completeness' sake, it would be worth baking an image in amigo CODE and then launching it somewhere to see it running end to end. I'll do that before merging for sure
The single instance that cannot currently connect to wazuh will indeed connect …

Add support for single instance configs

---

roles/teamcity-agent/tasks/main.yml

This disables [systemd-resolved](http://manpages.ubuntu.com/manpages/bionic/man8/systemd-resolved.service.8.html) as the default DNS resolver on teamcity-agent. Systemd resolved was introduced in ubuntu bionic, and is causing problems for docker containers running on teamcity.
The Systemd dns resolver modifies  /etc/resolve.conf - which is also consumed by docker. Docker doen't understand the local IP address systemd generates (as it's only accessible on the host) and so switches to using google's DNS servers (8.8.8.8). This fails (I think) because the agents are in a private subnet.
For a massive discussion of this bug see [this github thread](https://github.com/moby/libnetwork/issues/2187#issuecomment-403372190) - which also includes the solution I copy pasted 🥳 
I've tested this on …

Disable systemd DNS on teamcity

---

roles/friendly-hostnames/files/set-hostname.sh

[This role](https://amigo.gutools.co.uk/roles#friendly-hostnames) failed when trying to generate a new id using the hostnames.txt file, giving the following error on Ubuntu Bionic:
```
iconv: illegal input sequence at position 0
```
Ubuntu Bionic has iconv version 2.27, while Xenial is 2.23. Bionic has a version of iconv that is seemingly stricter with invalid character encoding so this fix skips over invalid ones:
```
Output control:
-c                         omit invalid characters from output
```

Fix reading of friendly hostnames file for Bionic

---

roles/teamcity-agent/meta/main.yml
roles/teamcity-agent/tasks/main.yml

This adds java8 and java11corretto as dependencies of the teamcity agent role, then adds a step to the agent role to set the default  java version, using [update-alternatives](https://linux.die.net/man/8/update-alternatives) to java8.
This will allow teams to optionall build stuff with Java 11 on teamcity.
Unfortunately, the SBT runner appears to ignore the java version set by update-alternatives. When I ssh onto a box and run `java -version` the correct version is returned, but sbt runner builds, which are set to <default> java (`JAVA_HOME environment variable or the agent's own Java.`) end up using java11.
In order to work round this issue, I think I will need to set a global JAVA_HOME environment variable in teamcity which people can optionally override. I am open to alternative …

Install Java 8 and Java 11 on teamcity-agent

---

app/controllers/BaseImageController.scala
app/controllers/RecipeController.scala
app/prism/RecipeUsage.scala
app/views/fragments/recipeTable.scala.html
app/views/fragments/usedByTable.scala.html
app/views/recipes.scala.html
app/views/showBaseImage.scala.html
test/prism/RecipeUsageSpec.scala

This changes the recipes and baseimageussage lists so that they have 2 sections - one for recipes in use (with an active instance or launch configuration), and one for unused recipes.
As part of this work I added a new `getUsagesMap` function which simplifies somewhat the calls  to RecipesUsage from the Recipes/BaseImage controllers.
This should make it easier to see which end of life recipes we need to worry about, and also easier to clean out unused recipes.
I've tested this on CODE - it should just be a UI change. See screenshots below

Show unused recipes separately

---

roles/teamcity-agent/tasks/main.yml

This modifies the teamcity agent role so that it doesn't use update-java-alternatives, as this fails  with the error below
```
sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
```
Run an amigo bake on code then cmd+f the build log for `update-alternatives`
Java 8 becomes default  version on teamcity AMIs.

Don't try and set plugin alternatives for java

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/event/Behaviours.scala
app/housekeeping/utils/BakesRepo.scala
app/models/Bake.scala
app/models/NotificationConfig.scala
app/notification/BakeFailedNotifier.scala
build.sbt
cloudformation.yaml

This PR wires AMIgo up to [Anghammarad](https://github.com/guardian/anghammarad) so that it can send email notifications when a bake fails. Right now this feature relies on the 'request encrypted copy'  feature to identify who owns a recipe - it will only send notifications to the owners of AWS accounts to which an encrypted copy has been requested.
For example, in the screenshot below failure notifications woul be sent to account  095
Tested on CODE. This is a backend only change. An example of the output notification can be seen below:

Notify upon bake failure

---

app/packer/PackerRunner.scala
app/services/AmiMetadataLookup.scala
build.sbt
roles/cdk-base/README.md
roles/cdk-base/tasks/main.yml

With the CDK work we want to usher in a new way of working with infrastructure. One of the experiments is migrate identity discovery and configuration to local disk. Whether the compute is EC2, ECS or Lambda - identity and config will live in one or possibly two well known locations.
This role bakes in the [instance-tag-discovery](https://github.com/guardian/instance-tag-discovery) tool that runs automatically at instance launch that fetches the tags from the related ASG or directly from the instance if there is not an ASG. They are written both as JSON and Java properties into `/etc/config/tags.json` and `/etc/config/tags.properties` respectively.
The package uses cloud-init's per-instance script folder to execute at instance launch.
Have confirmed that this works when IDMSv2 is …

Add a cdk role with tag discovery as a starter for 10

---

roles/wazuh-agent/tasks/main.yml

This sets up the wazuh agent role so that when registering an agent with the wazuh server it includes the AMI ID as a [wazuh label](https://documentation.wazuh.com/current/user-manual/capabilities/labels.html)
We will be able to aggregate vulnerabilities by ami id
My bash could be dodgy and break the wazuh agent role script 😱  but it's all copy pasted so 🤞🏻

Add AMI ID label to wazuh agent role.

---

roles/wazuh-agent/tasks/main.yml

Reverts guardian/amigo#587
This worked in CODE and on a single test instance, but in our services (I tried amiable and amigo) the aws cli calls now fail with a memory allocation error.
```
$  aws autoscaling describe-auto-scaling-instances
[SSL] malloc failure (_ssl.c:2805)
``` 
Very strange! Here's the full log output for reference
```
Jun 07 15:40:53 authenticate-with-wazuh-manager.sh[910]: + '[' -f /var/ossec/etc/authd.pass ']'
Jun 07 15:40:53 authenticate-with-wazuh-manager.sh[910]: + MANAGER_ADDRESS=xxxx
Jun 07 15:40:53 authenticate-with-wazuh-manager.sh[910]: ++ sed 's/.$//'
Jun 07 15:40:53 authenticate-with-wazuh-manager.sh[910]: +++ curl -s -X PUT http://169.254.169.254/latest/api/token -H 'X-aws-ec2-metadata-token-ttl-seconds: 21600'
Jun 07 15:40:53 …
```

Revert "Add AMI ID label to wazuh agent role."

---

roles/wazuh-agent/tasks/main.yml

This is a hotfix for the issue highlighted in #588. Turns out the revert didn't fix the issue, so it wasn't the original PR that introduced it. The cause for the issue is related to these package changes
Here's the full output with `--debug` flag, where we can see the aws command fails on its attempt to make an https request
```
++ aws autoscaling describe-auto-scaling-instances --debug --region eu-west-1 --instance-ids i-xxxxxxx --output text --query 'AutoScalingInstances[0].AutoScalingGroupName'
2021-06-08 13:20:44,352 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.19.12 Python/3.6.9 Linux/5.4.0-1049-aws botocore/1.20.12
2021-06-08 13:20:44,352 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['autoscaling', 'describe-auto-scaling-instances', …
```

Hotfix wazuh

---

roles/teamcity-ivy-cache/README.md
roles/teamcity-ivy-cache/files/sync-ivy-cache
roles/teamcity-ivy-cache/tasks/main.yml

As it turns out, the `teamcity-ivy-cache` role _is_ used. The `teamcity-agent` role [imports](https://github.com/guardian/amigo/blob/cabb7d47ae83c6ca87650681b382a41af7434022/roles/teamcity-agent/tasks/main.yml#L77-L79) it. This PR reverts https://github.com/guardian/amigo/pull/593 and updates some documentation for clarity.

revert: "chore: Remove unused teamcity-ivy-cache role" #593

---

cloudformation.yaml

Our current best practice is to retrieve the distribution bucket from Parameter Store.
This change updates the main template, adding a new parameter with a default value of the standard location. It also adds a comment to a somewhat confusing policy for future reference.
This is part of the preparation work to move this stack definition into CDK.
See:
- https://github.com/guardian/cdk/blob/main/docs/005-default-parameter-store-locations.md

refactor: Use Parameter Store for dist bucket

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Builds on https://github.com/guardian/amigo/pull/598.
Moving the `SSMRunCommandPolicy` resource into the CDK stack.
This is chosen because it's fairly easy to test if it works: if successful, we can continue to connect to an instance using ssm-scala.
AMIgo's stack defines two additional actions over the standard `GuSSMRunCommandPolicy`:
1. ssm:StartSession
2. ssm:TerminateSession
Slightly annoyingly, `GuSSMRunCommandPolicy` is a singleton and doesn't accept additional input. Therefore, we have to add these actions into a new statement on the policy.
`GuSSMRunCommandPolicy`'s `Roles` array is kinda hilarious (see snapshot test change). The good news is it's done by AWS CDK magic, so should work!
- Perform a full deploy of this branch on CODE
- Attempt to connect to one of the instances …

feat: Define `SSMRunCommandPolicy` in the CDK stack

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Follows #600.
This change replaces the YAML defined log shipping policy with the GuCDK's `GuLogShippingPolicy` construct.
`GuLogShippingPolicy` also brings a Parameter Store driven parameter into the stack, which replaces `KinesisStreamName`.
- Perform a full deploy of this branch
- Witness logs continuing to be shipped into Central ELK

feat: Use GuCDK's log shipping policy construct

---

project/plugins.sbt

I noticed that the `buildNumber` marker in the logs is currently `unknown`.
The value of this comes from [`sbt-riffraff-artifact`](https://github.com/guardian/sbt-riffraff-artifact). I'm not sure when, so bumping it to the latest.
- Observe logs in Central ELK
OR
- See images below
Our log lines are more accurate.

chore: Update `sbt-riffraff-artifact` plugin

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Replace the YAML resource that allows the instance to download the artifact from S3 with a GuCDK construct.
This has a secondary benefit where we follow the principle of least privilege as GuCDK [tightly scopes](https://github.com/guardian/cdk/pull/259) the `s3:GetObject` permission.
Perform a full deploy of this branch. If you can, then we can still get the correct files from S3 🎉 .
We move closer to a CDK only template and have tighter access policies.
The AMIgo application code might require access to the bucket on a path different from `bucket/stack/stage/app/*`. I can't see anything obvious to this effect though, so it should be ok.

feat: Move to GuCDK's policy to get the artifact 

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

An app's identity is defined by the App, Stack and Stage tags.
This change uses the `GuDescribeEC2Policy` construct to allow an app to know it's identity, replacing the YAML definition.
In using the construct, we're also creating the policy as a resource in its own right. This is preferred as it follows the single responsibility principle.
The `GuDescribeEC2Policy` construct grants the following permissions on `"*"`:
- autoscaling:DescribeAutoScalingInstances
- autoscaling:DescribeAutoScalingGroups
- ec2:DescribeTags
- ec2:DescribeInstances
That is, there is an additional `ec2:DescribeInstances` permission being granted.
I think we can test this by observing log lines as it looks like the logs' [identity based markers](https://github.com/guardian/amigo/blob/ccd7aba578bd302a …

feat: Define EC2 policies with GuCDK construct

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock
cloudformation.yaml

This change moves the Anghammarad permissions into the CDK defined stack.
The permissions get created as a policy in its own right, rather than statements on a generic "amigo-app" policy.
This results in a LOC increase to the resulting CFN template. That is, we're increasing the chance of reaching the CFN template limit!
This stack is pretty small, we should adjust strategy only when needed.
The change set includes changes to `cdk/package.json` and `cdk/yarn.lock` because `@guardian/cdk` has been updated to get the new construct (see https://github.com/guardian/cdk/pull/626).
We only [talk to Anghammarad](https://github.com/guardian/amigo/search?q=%22Anghammarad.notify%22) on bake failure at the moment.
I've tested this by creating a bake in CODE that installs an invalid …

feat: Move Anghammarad policy into CDK

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cloudformation.yaml

We have the HSTS header set for the CODE and PROD domains.
The HSTS header results in user agents always using HTTPS (443).
Not all user agents observe the HSTS header (e.g. curl), however:
- We only use AMIgo via the browser, which does observe HSTS
- AMIgo can still be accessed over HTTPS (443)
Fairly simply - the app should still be accessible after deploying this branch.
A smaller CFN stack.

fix: Remove redundant port 80 load balancer access

---

cdk/README.md
cdk/bin/cdk.ts
cdk/package.json
cdk/script/diff

The `cdk diff` command will compare a CDK stack against one running in AWS.
By default, `cdk` will use the `id` argument as the AWS stack name. That is, by default `cdk` will try to compare against the AWS stack "AMIgo".
This change creates a script that will read the stack name from an envvar instead, wrapping it all up in a new script for ease.
You can run `./script/diff` to compare against the CODE stack in AWS, or `./script/diff --prod` to compare against the PROD stack in AWS.
The script will also check your credentials as `cdk` seems to just hang if your credentials are invalid.
<details>
<summary>Example output</summary>
```console
➜ ./script/diff
yarn run v1.22.10
warning package.json: No license field
$ cdk diff --path-metadata false --version-reporting false
Stack AMIgo …
```

feat: Add `diff` script to easily compare against AWS

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock
cloudformation.yaml

Migrates the `AmigoDataBucket` resource into the GuCDK version of the stack.
In order to do this, we need to also move any resource that references `AmigoDataBucket`. There's only one resource `AmigoAppPolicy`.
Whilst we could migrate `AmigoAppPolicy` in this change too, it's preferable not to as the change set is pretty big and difficult to reason about.
I couldn't work out how to mutate a YAML defined resource from within CDK, so instead an additional policy is being added. I plan to migrate the remaining policies defined in `AmigoAppPolicy` to it in the next PR.
One thing to note is the bucket name is "changing" from a `Fn::Sub` to a mapping lookup, it still resolves to the same value. This causes `cdk diff` (via …

feat: Move the data bucket into the GuCDK stack

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Requires #622.
Migrates the policies that allow AMIgo to [create DynamoDb tables](https://github.com/guardian/amigo/blob/3496a1ba7d90ff1339e0f297d966a63ed25a4ce3/app/data/Dynamo.scala) from the YAML template into the CDK stack.
Pretty difficult really, as AMIgo doesn't need to create any more tables...
Maybe review the diff in the snapshot test to see if they result in the same permissions?

feat: Migrate policies that grant access to DynamoDb

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Requires #623.
Migrates the policy that allows access to configuration in DynamoDb.
Deploy this branch to CODE, it should succeed as app will not start if it cannot fetch config.

feat: Migrate configuration access policy

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Requires #625.
Migrates the policies that allow writing to SNS topics that trigger AMI deletions.
I've combined two individual polices into one, using an array of resources as the reason for the policies existing are the same.
The AMI deletion feature should still work!

feat: Migrate permissions to trigger AMI deletions

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Requires #626.
I don't fully understand the implementation of the image copier feature! In this change I'm (somewhat blindly) moving the policy from the YAML template into the CDK stack. It should be a no-op.
As mentioned above, I don't really understand this feature to conclusively say. Help wanted!
We can see from the snapshot diff, however, that the only change is where the policy gets defined. That is, I'm confident this is a no-op.

feat: Migrate policy for ImageCopier

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

Requires #627.
Migrates the Packer SSM policy from the YAML template to the CDK stack.
If this change isn't correct, I think the result would be an inability to bake any recipe. So, to test, try to bake a recipe?
We move closer to a CDK only template - the YAML defined `AmigoAppPolicy` is completely migrated 🎉 .

feat: Migrate Packer instance profile policy statement

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock
cloudformation.yaml

Adopting the VpcId stack parameter into the CDK stack allows us to start moving the YAML defined resources that reference this parameter in the CDK stack (for example the [`PackerSecurityGroup`](https://github.com/guardian/amigo/blob/158729df183d1d1bd284a9e74e0f24ad1dff027f/cloudformation.yaml#L177-L194)).
Deploy the app, it should still work!
Unblocking us from moving more YAML defined resources into CDK.
As we're moving from a direct parameter to a SSM parameter, we need to be sure the values are the same. I've just checked this and they are.

chore: Adopt VpcId stack parameter into CDK stack

---

app/controllers/RootController.scala
app/management/BuildInfo.scala
build.sbt

The build info has useful information that aides debugging. Specifically the commit hash which helps one determine exactly what version of the app is deployed.
This doesn't impact the AWS healthcheck as the status code remains the same - only the response body changes.
- Deploy this branch
- Visit `/healthcheck`
- Witness some lovely JSON

feat: Expose build info on `/healthcheck`

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cloudformation.yaml

This change moves the YAML defined `PackerSecurityGroup` into the CDK stack. There is ultimately one change being made, the `AWS::EC2::SecurityGroup Egress` gets a description. The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html#cfn-ec2-security-group-rule-description) state this isn't a replacement operation 🎉 .
Deploy and bake - the bake should start.
Moving closer to a CDK only defined stack.

feat: Migrate `PackerSecurityGroup` into CDK stack

---

app/components/AppComponents.scala
app/services/ELKLogging.scala

This will allow us to determine which instance is sending logs, which is of particular use for the YAML -> CDK migration.
There are a lot of whitespace changes in this diff, so it'll be easier to review [w/out them](https://github.com/guardian/amigo/pull/634/files?diff=split&w=1).
- Deploy this branch
- Check logs, they should have a new marker
This will allow us to determine if the new instances launched in #632 have the correct permissions.

feat: Add the instanceId as a log marker

---

app/housekeeping/MarkOldUnusedBakesForDeletion.scala
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala

Follow-up to https://github.com/guardian/amigo/pull/553, as the TeamCity Agent AMI has changed slightly since that PR was merged.
Obviously this is still a hack, but hopefully it'll keep things stable until [this card](https://trello.com/c/unohWhlM/728-auto-update-teamcity-build-agents-ami) can be worked on.

Prevent AMIgo from removing TeamCity AMIs

---

app/housekeeping/MarkOldUnusedBakesForDeletion.scala
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala

* Now that we have a process for automatically updating TeamCity Agent AMIs (see https://github.com/guardian/deploy-tools-platform/pull/528), we can remove a hack that was added to prevent AMIgo from deleting old TeamCity AMIs (see https://github.com/guardian/amigo/pull/553)
* Should be covered by [existing unit tests](https://github.com/guardian/amigo/blob/daee87ab85fbcd9774db21b96ebaa2acf576ee24/test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala)
* We no longer retain stale AMIs unnecessarily 
* Yes, there is a risk that TeamCity Agent AMI bakes / the new automated upgrade process will fail. Without this hack it's possible that we will end up in a situation where TeamCity agents cannot be launched. However, I think existing AMIgo/AMIable monitoring should be sufficient to …

Allow AMIgo to remove old TeamCity AMIs

---

roles/python3.7-pip-virtualenv/README.md
roles/python3.7-pip-virtualenv/meta/main.yml
roles/python3.7-pip-virtualenv/tasks/main.yml

Adds an ansible role that installs:
- `python3.7`
- `pip3`
- `virtualenv` for Python 3
Installs Python 3.7 as a longer support option compared to the system Python 3.6 (EOL: [27 Jun 2023 vs. 23 Dec 2021](https://endoflife.date/python)).
I am open to replace it with Python 3.8 as an even longer support option.
This role does **not** overwrite the Python 3.6 version installed via `apt-get install python3`, hence it will not conflict with any of the other Python 3 roles in this repo (`pip3`, `pip3-packages`).
The following symlink will remain intact:
`/usr/bin/python3` --> `/usr/bin/python3.6`

Add role that installs Python3.7 and virtual environment

---

roles/browser-testing/README.md
roles/browser-testing/tasks/main.yml

Currently [guardian/editorial-tools-production-monitoring](https://github.com/guardian/editorial-tools-production-monitoring) breaks with Chrome 92 (see https://trello.com/c/8tvMxMRX/2446-investigate-why-prodmon-breaks-w-the-latest-ami-and-fix for all the things we've tried in order to resolve). As such we had to remove the `ami-cloudformation-parameter` deployment step (see https://github.com/guardian/editorial-tools-production-monitoring/pull/281) so prodmon is not using the latest AMI, as it includes Chrome 92 (because it is 'latest').
This PR makes the version of Chrome (and chromedriver) configurable (falling back to _latest_ if unspecified), so that we can specify Chrome 91 (which is the company wide version at the moment anyway) until there's a compatible & stable version of …

[role: `browser-testing`] make version of Chrome and chromedriver configurable (falling back to 'latest')

---

roles/puppeteer/tasks/main.yml

We observed that Time Machine stopped working, and went to find some
errors in the logs.
We saw this error:
```
java.lang.RuntimeException: External process failed with error output: (node:9347) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! /node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/node_modules/puppeteer/lib/Launcher.js:339:14) at Interface.helper.addEventListener
```
Which prompted us to see if updating the version of libgtk-3-0 by ssh-ing
directly onto the time machine box would get time machine up and running
again. It …

Add libgtk3 dependency to puppeteer role & upgrade puppeteer

---

roles/puppeteer/tasks/main.yml

Decouples Puppeteer upgrade from the libgtk-3-0 upgrade that was in this PR: https://github.com/guardian/amigo/pull/644 
libgtk-3-0 was needed to get Time Machine working again. We were hoping to upgrade Puppeteer too while we were there, but that seems to be a bit more involved and should probably be decoupled from the libgtk-3-0 upgrade. We tried manually updating libgtk-3-0 and puppeteer before shipping https://github.com/guardian/amigo/pull/644 - process described here https://github.com/guardian/ophan/issues/3932#issuecomment-904571290 
Post merge we should do the same checks:
Time machine works again. 
Yes, only we use the puppeteer role currently.

Downgrade puppeteer version back to 1.9.0

---

roles/ssh-reserve-disk-space/tasks/main.yml

This changes 3 things
1. moves image files to `/var/lib/reserved-disk`
2. Reserves 50mb instead of 10mb
3. Retains `/var/lib/amazon/ssm`'s original permissions, which are `drwxr-x---`

Tweaks to ssh reserve space

---

roles/python3.7-pip-virtualenv/README.md
roles/python3.7-pip-virtualenv/meta/main.yml
roles/python3.7-pip-virtualenv/tasks/main.yml

Remove bespoke apt package installation role (`python3.7-pip-virtualenv`) as the same can be achieved with the [`packages` role](https://amigo.gutools.co.uk/roles#packages) as per conversation: https://chat.google.com/room/AAAAag0I08g/m7WVe37Wqls

Revert PR #640

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock

This PR brings `cdk` dependencies up to date.
I've deployed this to `CODE` to confirm that the app still works as expected.
* We are using up to date versions of `cdk` dependencies
* The path for testing new `cdk` features on this project is unblocked
Yes, snapshot changes are minimal (and expected) and this PR has been tested in `CODE` so this should be pretty safe.

Upgrade to @guardian/cdk 29.0.0 and @aws-cdk 1.132.0

---

cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock

This PR brings the `@guardian/cdk` dependency up to date. The main goal here is to pick up the changes in https://github.com/guardian/cdk/pull/912.
I've deployed this to `CODE` to confirm that the DNS record is not modified in any way. I've also confirmed that the only update to the certificate relates to tagging.
* We are using the latest version of `@guardian/cdk` and following best practice for self-service DNS.
Yes, the snapshot tests indicate that there are no changes and this PR has been tested in `CODE`.

Use new CNAME construct

---

cdk/bin/cdk.ts
cdk/package.json
cdk/script/diff
cdk/yarn.lock

Brings in https://github.com/guardian/cdk/pull/919 and copes with the breaking change.
* CI
* I've also run `./script/diff` locally and confirmed that the only changes relate to tagging
* We are using the latest version of `@guardian/cdk`
* This should be low risk due to testing described above

Use @guardian/cdk 31.0.0

---

roles/wazuh-agent/tasks/main.yml

Replaces https://github.com/guardian/amigo/pull/659  - text below copied from @louishather PR
Wazuh agents currently use version 3.13.1, and while they shouldbe upgraded as a matter of course, version 4.x offers a number of benefits, specifically around the lifecycle of agents and managers.
To change the version the apt source for wazuh-agent was set to 4.x, rather than 3.x. 
The role pulls SSM parameters to retrieve agent config, and specific wazuh-agent version. If the agent version parameter isn't changed when this change is merged, AMIs that use the wazuh-agent role will fail to build.
Applying this change needs coordination to change the SSM parameter values simultaneously.

Bump wazuh repo version

---

roles/wazuh-agent/tasks/main.yml

Not 100% confirmed yet, but there's a strong possiblity that this change is making instances unhealthy on boot.
Reverts guardian/amigo#660

Revert "Bump wazuh repo version"

---

roles/aws-tools/tasks/install-cfn-tools-Debian.yml
roles/aws-tools/tasks/install-cfn-tools-Ubuntu-post-focal.yml
roles/aws-tools/tasks/install-cfn-tools.yml

This attempts to fix a bug we are seeing with installing aws-cfn-tools in AMIgo. It looks like an update to https://pypi.org/project/pystache/#history two days ago has broken the python2 version of the aws-cfn-tools - as pystache now only supports python 3. 
This PR (needs more description) aims to try using the latest version of the tools which support python 3

Try using pip3 to install aws-cfn-tools

---

build.sbt

This is part of the work to resolve the log4j remote code execution vulnerability.
It looks like `aws-lambda-java-log4j` is being used to ship logs from the imageCopier lambda into ELK. However this is handled by https://github.com/guardian/cloudwatch-logs-management already.
`cloudwatch-logs-management` will forward CloudWatch Logs to Central ELK. Therefore, the only requirement for a lambda to log into Central ELK is for it to write logs to CloudWatch Logs.
This is the default behaviour - `println`ing a message will be shipped to ELK automagically.
- Deploy and execute the lambda by baking an encrypted AMI
- Observe logs landing in Central ELK
Fewer dependencies and resolving the log4j RCE.

chore: Remove `aws-lambda-java-log4j` dependency

---

app/views/fragments/eolStatus.scala.html

While pairing with @philmcmahon earlier today we spotted that the label for end of life images was not displaying correctly.
This is because the `label-error` CSS class does not exist. This PR addresses the problem and makes the label readable.

Fix base image End of Life label

---

roles/security-patches/files/log4j-systemd.conf
roles/security-patches/tasks/main.yml

This sets a [verbose logging flag](https://github.com/corretto/hotpatch-for-apache-log4j2/pull/45/files) for the Log4j hotpatch JAR, which will silence some of the logging. In particular it prevents a message `Loading Java Agent version 1 (using ASM9).` upon startup.  This appears to be important in at least one edge case we've identified.
Namely, on Play <=2.5 the bash script that starts your service (provided by sbt-native-packager) has a java version check which fails when this message is printed during an execution of `java -version`. Strangely, this has been very difficult to reproduce manually, but I have verified that setting this flag does allow the service to start.
This hasn't appeared to be an issue in Play >=2.6 because the bash script was updated …

Set verbose to false for log4j patch agent

---

app/controllers/BaseImageController.scala
app/views/baseImages.scala.html

Adds the number of usages in recipes of a base image. This is useful to quickly see unused and less-used base images.
Deployed to CODE

Add base image usages to list view

---

roles/java17/meta/main.yml
roles/java17/spec/java17_spec.rb
roles/java17/tasks/main.yml

JRE17 has been supported by Scala for [some time now](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#version-compatibility-table) and notably the only version which works natively on [M1 ARM 64 architecture](http://openjdk.java.net/jeps/391).
This adds a role that should be a simple swap out for recipes switching from version `8` or `11`.
This impacts baked AMIs so best tested by converting an AMI over.
See #548

Add JDK 17 as a role

---

roles/java11corretto/README.md
roles/java17corretto/README.md
roles/java17corretto/meta/main.yml
roles/java17corretto/spec/java17corretto_spec.rb
roles/java17corretto/tasks/main.yml

Adds Corretto's Java 17. See also https://github.com/guardian/amigo/pull/678.
We should probably go further than this and actually express a clear preference over which Java distro to use. But that is beyond the scope of this PR.
cc @philmcmahon .
Tested locally.

Add corretto 17 role

---

roles/wazuh-agent/defaults/main.yml
roles/wazuh-agent/tasks/main.yml

This is another attempt at upgrading the wazuh-agent version, as #662 reverted the previous attempt. This was reverted as the wazuh-agent didn't start up, so there must have been changes to its default systemd configuration. There's now a task to explicitly enable the agent was part of the wazuh-agent role.  
Rather than use the script to retrieve the (non-secret) version from SSM, I've included it in the roles defaults file. This will mean future version upgrades can be tested without changes to the role or parameters in SSM - we can instead change the value for the base images. 
From #659 
> Wazuh agents currently use version 3.13.1, and while they shouldbe upgraded as a matter of course, version 4.x offers a number of benefits, specifically around the lifecycle of agents and managers. …

Upgrade wazuh-agent to 4.x returns

---

build.sbt

Upgrades `quartz` to avoid a vulnerability and bring things up to date.
I've deployed this to `CODE` and confirmed that a scheduled bake is still triggered by inspecting the [logging](https://logs.gutools.co.uk/s/devx/goto/1fbe1850-7de4-11ec-b6e1-55bd2b673f28). Scheduled bakes [don't actually run](https://github.com/guardian/amigo/blob/61f44c2f6f6ba6e67310f8982c299e533edbc3f5/app/components/AppComponents.scala#L228-L232)  in `CODE`!
We should have fewer vulnerabilities in Snyk as a result of this PR.
I don't think this PR is especially risky given the testing performed.

Use latest version of quartz

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/controllers/BaseImageController.scala
app/controllers/RecipeController.scala
app/event/Behaviours.scala
app/housekeeping/BakeDeletion.scala
app/housekeeping/MarkOldUnusedBakesForDeletion.scala
app/housekeeping/MarkOrphanedBakesForDeletion.scala
app/packer/PackerRunner.scala
app/prism/RecipeUsage.scala
app/schedule/ScheduledBakeRunner.scala
app/services/PrismData.scala
build.sbt
test/prism/RecipeUsageSpec.scala

Akka Agents are [deprecated in Akka 2.5.x](https://doc.akka.io/docs/akka/2.5.32/agents.html) (which this repo currently uses) and have been [removed](https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#removed-features-that-were-deprecated) completely in 2.6.x. Consequently, this PR removes the `akka-agent` dependency and uses `AtomicReference` instead, following the guidance (and code!) from https://github.com/guardian/box, which was the Guardian's initial replacement for Akka Agents.
There's a bit of noise in this PR due to renaming. The important change is [here](https://github.com/guardian/amigo/pull/686/files#diff-90b9ecce377f41a739fe88b5a599f38211626430fa009780e5f8ce01a138fe0f).
I've tested this by:
1. Deploying to `CODE`
2. Launching an EC2 instance from …

Remove dependency on akka-agent

---

app/models/Bake.scala
app/models/Recipe.scala
build.sbt

This repository was using https://github.com/cb372/automagic to reduce boilerplate when converting between models. This was pretty neat, but it's no longer maintained (and is not published for more recent Scala versions), so I've removed the dependency at the expense of some boilerplate.
I've deployed this to `CODE` and tested some basic functionality (creating a recipe, modifying a recipe, viewing recipes, viewing bakes, starting a new bake).
It will be easier to upgrade to a more recent Scala version without this dependency.
I don't think this PR is especially risky given the testing performed.

Remove automagic dependency

---

build.sbt
test/ansible/PlaybookGeneratorSpec.scala
test/ansible/RoleParserSpec.scala
test/data/PackageListTest.scala
test/data/RolesTest.scala
test/housekeeping/DeleteLongRunningEC2InstancesSpec.scala
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala
test/housekeeping/MarkOrphanedBakesForDeletionSpec.scala
test/housekeeping/TimeOutLongRunningBakesSpec.scala
test/models/BakeIdTest.scala
test/models/BaseImageTest.scala
test/models/CustomisedRoleTest.scala
test/notification/LambdaDistributionBucketSpec.scala
test/notification/SNSSpec.scala
test/packer/PackerOutputParserSpec.scala
test/prism/PrismSpec.scala
test/prism/RecipeUsageSpec.scala

This PR updates all test dependencies to ensure that we are using versions which are compatible with the most recent versions of Scala (we are hoping to upgrade soon).
There have been a couple of significant changes since these dependencies were last updated which makes this diff a little noisy (hence the separate PR):
* The library [has been modularised](https://www.scalatest.org/release_notes/3.1.0), which means that we can improve standardisation within the project by only including the [test styles](https://www.scalatest.org/user_guide/selecting_a_style) that we need.
* The library/approach for using ScalaTest with Mockito seems to have changed - I've followed the approach described [here](https://www.scalatest.org/plus/mockito).
CI should be sufficient for this PR.

Update test dependencies

---

app/controllers/BakeController.scala
app/controllers/ControllerHelpers.scala
app/data/BakeLogs.scala
app/data/Bakes.scala
app/data/BaseImages.scala
app/data/PackageList.scala
app/data/Recipes.scala
app/housekeeping/DeleteLongRunningEC2Instances.scala
app/housekeeping/utils/PackerEC2Client.scala
app/packer/PackerRunner.scala
app/services/AmiMetadataLookup.scala
build.sbt
test/housekeeping/DeleteLongRunningEC2InstancesSpec.scala
test/models/CustomisedRoleTest.scala
test/prism/RecipeUsageSpec.scala

This PR upgrades the project to use Scala 2.12. Key changes for this codebase include:
* [`Either` becomes right-biased](https://www.scala-lang.org/news/2.12.0/#either-is-now-right-biased), allowing us to remove some boilerplate (and some usages of `cats`)
* [`JavaConversions` is deprecated and replaced by `JavaConverters`](https://www.scala-lang.org/news/2.12.0/#other-changes-and-deprecations), which requires more explicit syntax for conversion between Java and Scala
Although this is not the latest Scala version*, it unblocks a couple of key upgrades:
* Play Framework version 2.8.x, which [drops 2.11 support](https://www.playframework.com/documentation/2.8.x/Migration28#Scala-2.11-support-discontinued)
* Recent versions of [`play-google-auth`](https://github.com/guardian/play-googleauth) …

Upgrade to Scala 2.12

---

.github/workflows/ci.yaml
build.sbt
cdk/script/ci
project/plugins.sbt
script/ci

This PR configures GitHub Actions for AMIgo (as a replacement for [TeamCity](https://teamcity.gutools.co.uk/admin/editBuildRunners.html?id=buildType:Tools_Amigo)).
I've deployed a branch built via GitHub Actions to `CODE`.
All configuration related to CI is now in version control.
Yes, CI performance may be slightly worse on GitHub Actions. As there are plans to address that over the next few months I'm not especially concerned about it.

Migrate to GitHub Actions for CI

---

app/components/AppComponents.scala
build.sbt
cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
cdk/package.json
cdk/yarn.lock

This PR adds the [`play-secret-rotation`](https://github.com/guardian/play-secret-rotation) library to this project, which allows us to rotate our [Play Application secret](https://www.playframework.com/documentation/2.8.x/ApplicationSecret) regularly, without impacting users 🎉 
This allows us to improve security and avoid deprecation warnings when upgrading [`play-googleauth`](https://github.com/guardian/play-googleauth).
I've deployed this to `CODE` and [tested rotating the Play application secret](https://logs.gutools.co.uk/s/devx/goto/5a2d4fa0-8821-11ec-9387-7946d531de16).
It's easy to rotate our application secret whenever we need to. 
That said, I'm not completely sold on the [final recommendation made by the `play-secret-rotation` …

Add play-secret-rotation

---

roles/cloudwatch-hardware-monitoring-cronjob/tasks/main.yml

cloudwatch-hardware-monitoring-cronjob is useful for checking memory/disk usage of an app over time. Especially useful in reservation season! 
Currently the outputted command from this role is broken, it messes up the --disk-path parameters.
For example, for the paths input `paths: [/, /data]` it generates a command like this:
`/usr/local/aws-scripts-mon/mon-put-instance-data.pl    --disk-space-util  --mem-util --disk-path /--disk-path  --disk-path /data--disk-path`
If you look closely at ^ you can see there are a load of erroneuous `--disk-path` strings, and worse there's no space between then and the paths, resulting in very dodgy paths. We get an error when running this command:
`Disk file path '/--disk-path' does not exist or cannot be accessed.`
This change fixes it. I'm not sure …

Fix cloudwatch-hardware-monitoring-cronjob role

---

roles/teamcity-agent/tasks/main.yml

Add ARM support to the `teamcity-agent` role so that we can switch to Graviton.
Simple local testing seems difficult on an M1 mac (no virtualbox) and having issues running the main app locally too, so testing on CODE for now.

Update teamcity-agent role to work on ARM

---

.github/workflows/ci.yaml
app/components/AppComponents.scala
app/controllers/BakeController.scala
app/event/BakeEvent.scala
app/event/Behaviours.scala
app/views/showBake.scala.html
build.sbt
conf/routes
public/javascripts/show-bake.js
public/stylesheets/main.css

This PR is preparation for upgrading to Scala 2.13
Amigo uses  the Play "iteratees" and "reactive-streams" libraries to surface the logs in real time on the  "show-bake" pages for a bake that is in progress.
These libraries have reached their end of life and do not have a version supported in Scala 2.13.
In later versions of Play, Akka streams are used in place of the reactive streams used to-date. However the implementation of these is different enough to be non-trivial.
It was also determined that live-streaming the logs for a bake that can often take 20 minutes to complete was not of great value as it is unlikely to be watched for that long. The logs are loaded when the page is refreshed after completion of bake - which is  when a user is most likely to be looking at them in any case. …

Remove Log streaming from showBake page

---

.github/workflows/ci.yaml
app/components/AppComponents.scala
app/controllers/BakeController.scala
app/event/BakeEvent.scala
app/event/Behaviours.scala
app/views/showBake.scala.html
build.sbt
conf/routes
public/javascripts/show-bake.js
public/stylesheets/main.css

Reverts guardian/amigo#700
We have discovered an issue with this PR, The removal of the event source in line:
https://github.com/guardian/amigo/pull/700/files#diff-275086bef5d49fdfbb4cdd7573d272b5cc4facdc931fff59175d3e8cd1ddf5eeL209
will prevent the creation of encrypted copies of AMI's

Revert "Remove Log streaming from showBake page"

---

app/models/CustomisedRole.scala
build.sbt
test/models/CustomisedRoleTest.scala

This change is part of the update to scala to 2.13 work.
In order to proceed with this we need to update the fastparse library to its latest version.
Because this required some significant refactoring of the CustomisedRoles object, I have split this work out into this PR.
Trello card is here:
https://trello.com/c/PsPsHZvF/1138-amigo-upgrade-scala-and-sbt-versions

update fastparse to latest version 2.2.2

---

.gitignore
README.md
multipass/playbook.yaml
multipass/run.sh
roles/cdk-base/README.md
roles/cdk-base/meta/main.yml
roles/cdk-base/tasks/main.yml

**Note, this is being trialled in DevX and not ready for other teams yet, but please shout if interested in testing it.**
See role README for more info.
Eventual plan is to include this in the standard base images, but that can be in a subsequent PR once we've tested thoroughly and are convinced it's the right approach.
Initially devx-logs ships Cloud Init Output, but will be extended to application logging too in the near future.
See also:
* [instance-tag-discovery](https://github.com/guardian/instance-tag-discovery)
* [devx-logs](https://github.com/guardian/devx-logs)
And these related PRs:
* https://github.com/guardian/instance-tag-discovery/pull/3
* https://github.com/guardian/amigo/pull/710

Introduce devx-logs

---

roles/cdk-base/defaults/main.yml

Follows https://github.com/guardian/amigo/pull/706, which is fine but will fail the bake is the var isn't defined. 
Note, the bucket is already described in Amigo's code so this isn't a secret.

Default dist_bucket var

---

roles/cdk-base/tasks/main.yml

Ensure fluentbit is started as part of cdk-base. Arguably the Fluentbit role itself should do this, but am wary of changing its existing behaviour here as there are already a number of production users.

Enable fluentbit to ensure startup in cdk-base

---

roles/oauth2-proxy/tasks/main.yml

While moving our Kibana instance from amd64 to arm64, I discovered that oauth2-proxy will silently fail (AMIgo will happily install it, but the binary is not built for ARM, so the service fails to start). This PR fixes installs for arm64.
This adds 2 steps to the oauth2-proxy role, which will conditionally pull down an arm64 version of oauth2-proxy if ansible_architecture == "aarch64". I've also added conditionals to existing tasks, so the amd64 version will only be installed on amd64. 
This should be an improvement over the existing tasks, as although we're unlikely to need oauth2-proxy outside of amd64/arm64, the role was unaware that it had installed an unusable version (amd64 on arm64) of oauth2-proxy. In future, if this role is run on say, sparc, the task which moves the resulting …

Make oauth2-proxy role work for ARM

---

cdk/package.json
cdk/yarn.lock

This PR is a follow-up in response to https://github.com/guardian/amigo/pull/719#discussion_r853198747; the snapshot tests indicate that there are no infrastructure changes introduced by this upgrade.

Use official release of @guardian/cdk

---

.gitignore
roles/cdk-base/README.md

Make cdk-base readme less scary and also more informative.

Improve cdk base readme

---

roles/mongo-helper-scripts/meta/main.yml
roles/mongo-helper-scripts/tasks/main.yml

These are not used.
It looks like they were originally [added](https://github.com/guardian/amigo/pull/87) for flexible-content, which has now [migrated to Postgres](https://www.theguardian.com/info/2018/nov/30/bye-bye-mongo-hello-postgres).

Delete roles/mongo-helper-scripts directory

---

roles/teamcity-agent/defaults/main.yml
roles/teamcity-agent/tasks/main.yml

We recently attempted to upgrade `nvm` (partly to keep things up to date and partly in an attempt to fix failing AMIgo bakes): https://github.com/guardian/amigo/pull/389.
Although this [fixed the AMIgo bakes, it caused unexpected problems with many of our builds](https://github.com/guardian/amigo/pull/389#issuecomment-1127501180).
This PR reverts to `nvm` version 0.33.11* and updates the way that we install the default version of Node to workaround the problems that we were seeing with our AMIgo bakes. 
The old method installed the 'current' (i.e. latest) version of Node _and_ the latest version of Node under long-term-support. [Recently, the 'current' version of Node has changed to Node 18](https://nodejs.org/en/about/releases/):
The fact that we are now trying to install Node 18 seems …

Rollback to nvm 0.33.11 and specify default Node version (16)

---

roles/cdk-base/README.md

Reverts guardian/amigo#733
Turns out its not 'safe' to use `cdk-base` on recipes which use fluentbit (with their own config) rather than `devx-logging` (see for example https://github.com/guardian/path-manager/pull/52) - that can be investigated in due course (FYI @nicl @jacobwinch @akash1810 )
Reverting this for now.

Revert "[`cdk-base` role] README tweak"

---

roles/cdk-base/README.md

An update on #735 as I missed the review comment.
The `autoscaling:DescribeAutoScalingInstances` permission is not needed by `cdk-base`.
See https://github.com/guardian/amigo/pull/735#pullrequestreview-982786995.

docs: Update `cdk-base` permissions

---

roles/wazuh-agent/defaults/main.yml
roles/wazuh-agent/tasks/main.yml

This PR changes the role defaults for the wazuh-agent roles, changing the agent_version parameter from 4.1.5-1 to 4.3.1-1. Future wazuh-agents will be installed with the newer version. 
Restart behaviour was also added to make agents capable of registration if registration fails during initial startup. The impact of this is very low, with a frequency of 5 minutes. 
Wazuh-agent is installed on every build, so we should make sure this won't introduce any build failures, agent registration failures, or other instability. 
The impact of restarting the service was tested on a micro instance. Without a registration with the wazuh manager, it's extremely minimal, and once registered the service will not restart.

Upgrade wazuh-agent to v4.3.1-1

---

roles/wazuh-agent/tasks/main.yml
roles/wazuh-agent/templates/wazuh-agent.service.template

#737 introduced an issue where recipes failed to bake, as the path to the systemd service file was incorrect. This was changed between v4.1.5 and v4.3.1. In order for agents to register with the wazuh coordinator, the authentication script should be run before the service starts, which is achieved by inserting "ExecStartPre=/usr/local/bin/authenticate-with-wazuh-manager.sh" into the [Service] section of the service file. 
Previously we inserted a single line into the service file contained in the package. Now, instead of relying on the package version, a new systemd service file will be templated in /etc/systemd/system/wazuh-agent.service.
Builds no longer fail due to wazuh-agent lineinfile task not finding a file to edit at /lib/systemd/system/wazuh-agent.service.

Wazuh-agent role systemd service file fix

---

cdk/package.json
cdk/yarn.lock

This change updates cdk from 46.0.0 to 46.0.1 - this will resolve a critical vulnerability in the git-url-parse library.
There will be no other impact on the Amigo codebase.
Unit tests will provide sufficient confirmation of success.
Snyk vulnerability notification for git-url-parse will no longer be displayed on git reppository.

Resolve critical git-url-parse vulnerabiility by bumping cdk from 46.0.0 to 46.0.1

---

.github/workflows/ci.yaml
.github/workflows/dep-updates_pr-tracking-branch-to-default.yml
.github/workflows/dep-updates_set-automerge.yml
.github/workflows/dep-updates_tracking-branch.yml

Adds a series of workflows that enable granular dependency updates from e.g. Scala Steward. It works by automatically merging PRs from those tools into a non-default branch before creating a single PR on a specified schedule.

Add workflows to enable dependency update batching

---

.github/workflows/snyk.yaml

Avoids running unnecessary actions on PRs targeting the `dependency-updates` branch, which are intended to be reviewed/tested after being batched as a single PR targeting `main`.

Don't run Snyk on granular dependency update PRs

---

app/data/Bakes.scala

My guess is that the behaviour of 'limit' changed when Scanamo was updated at the end of March 2022 - a timeframe that corresponds to when we start seeing this fail.
It looks like Scanamo 'fixed' its behaviour to match what 'limit' means in Dynamo parlance. For more info, see:
- https://github.com/scanamo/scanamo/pull/996
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Limit
Note, this is more to confirm the source of the issue for now. A better long-term fix is to create a secondary index on the deleted field and then query against that to avoid the scans here.

Attempt (crude) fix of bake deletion housekeeping job

---

app/data/Bakes.scala

The Ops team recently observed a significant increase in AWS spend, which Cost Explorer analysis narrowed down to increased EBS usage.
The cause was an Amigo bug, following a Scanamo (Dynamodb client library) upgrade, which prevented the EBS cleanup job from running successfully.
An initial fix can be found here: https://github.com/guardian/amigo/pull/846.
This PR tweaks the fix to remove the limit entirely. This ensures the job does not miss any EBS volumes that should be deleted.  Specifically, it removes the 'limit' on the delete query to ensure we return and process all deleted bakes. The downside to this fix is that our processing job is unbounded, but in practice AMI numbers are low (100s not 1000s) so this shouldn't be a problem - though the initial deploy might cause an initial …

Remove limit from delete query

---

roles/kong-v1_5/files/kong.logrotate
roles/kong-v1_5/tasks/main.yml

Ubuntu 20.04 hardens the logrotate setup, preventing it from writing to most system locations. Unfortuntely, Kong keeps its logs under /usr/local/kong/logs so this must be explicitly allowed in the unit file.
Build on CODE and check that the files have the right contents (the `ReadWritePaths` should be added to `logrotate.service`).  Leave it overnight to check that the log files do, in fact, rotate correctly
Reliable log warehousing from Kong
n/a

Fix for hardened logrotate setup

---

riff-raff.yaml

It's no longer needed and this will remove the riff-raff warning.

Remove explicit bucket name

---

riff-raff.yaml

**This fixes the currently broken PROD deployment.**
The `aws-s3` deployment type which does not auto-lookup the bucket value in SSM, a previous change (https://github.com/guardian/amigo/pull/8790) removed the explicit. bucket name, this re-adds it to fix the issue.
This has been [tested in CODE](https://riffraff.gutools.co.uk/deployment/view/dc3aa1d5-1e9d-4acd-829c-4c78293259bf).

Add the bucket param for imagecopier deployment

---

roles/kong-v1_5/files/kong.logrotate
roles/kong-v1_5/tasks/main.yml

- Update the Kong role to make logrotate run hourly (within a +/- 5min window)
- Update the Kong logrotate rule to also run hourly
This is to alleviate a problem which we believe occurred due to disk pressure on the node. Since Kong is 3rd party software, we cannot directly push logs to Elasticsearch and must read them from disk via Logstash.
Check that the build works. Once you have a build, check that the logrotate process is still set up correctly and is now running every hour, round about `:00` minutes.
Improved Kong reliability
This simply modifies existing configurations for logrotate and the resulting configuration has been independently tested to work.  This makes "official" a temporary fix which was put into Kong earlier (https://github.com/guardian/content-api/pull/2714)

Change kong log purging frequency to hourly

---

app/components/AppComponents.scala
app/controllers/Login.scala
build.sbt
cdk/bin/cdk.ts
cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts
project/plugins.sbt

TODOs:
Introduce Google auth so that people can access the app behind a public DNS.
Note, the Google Project credentials have usage type set to 'Internal' to limit users to members of the guardian org. A group check has also been introduced to further limit access to P+E devs.
Usual approach of CODE/IP allowlist.

Add Google Auth

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

Follows https://github.com/guardian/amigo/pull/959 which introduced Google auth and group membership check.
WAF is enabled manually for now pending a more permanent solution.

Make public (behind Google auth)

---

app/packer/PackerRunner.scala
cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

Upgrade to v1.8.5. Older versions were running afoul of https://github.com/hashicorp/packer/issues/11733 when building images for ubuntu 22.04, eg. https://amigo.gutools.co.uk/recipes/editorial-tools-jammy-java8/bakes/1
This upgrade changed the default location Packer used for its cache directory. Instead of `${PWD}/.packer_cache` it switched to using `${HOME}/.cache/packer`. This shouldn't really have been a problem except that for reasons lost to history the AMIgo box specifies `/home/amigo` as home in `/etc/passwd` but this does not exist and packer was unable to create it.
We fix this by setting `$PACKER_CACHE_DIR` when executing packer and using isolated temp directories which are cleaned up along with the config and ansible files.
Teams can move to the latest Ubuntu LTS.

Upgrade packer to latest

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

This PR adds the ALB's ARN to parameter store so that it can be used/looked up by `cdk` stacks in https://github.com/guardian/waf.
See https://trello.com/c/Gf4wbq5Y/1716-configure-wafs-for-all-services-in-their-own-repository
Related: https://github.com/guardian/grafana/pull/216
[Deploy to `CODE`](https://public.riffraff.gutools.co.uk/deployment/view/66cb5180-2703-425b-9b0b-39517c15f168) to confirm that the parameter is created as expected.
This allows us to move forwards with the work to define a separate WAF for AMIgo via a different repository.

Create SSM parameter with ALB arn (for WAF configuration)

---

.github/workflows/snyk.yaml

Snyk no longer runs every day at 6am. This is unnecessary as it submits the same set of dependencies every day until somebody updates the repo, wasting action minutes.
I've also removed the pull request trigger, as we only want to know about vulnerabilities on the main branch. As well as this, we know a project is reliably integrated if the commit hash from the most recent workflow run matches what is on the head of main. Running this workflow on branches means that this will almost never be the case
Verify the workflow finishes successfully
Amigo will show up as reliably integrated on grafana

Remove scheduled and branch runs of snyk

---

roles/browser-testing/README.md

The link for `chrome_version` has an underscore in it, which conflicts with the other underscores on the line, ending the italics early
(Github markdown works correctly for this case; it notices that the link is a link and treats it as such; so the diff claims that there are no differences. I _think_ this will make Amigo's markdown parser behave the same)

Mark up URLs as URLs to get clickable links and avoid odd formatting

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a PR template for AMIgo, including a note that if you're modifying a role/recipe to note who it's impacting and get them to review it.  This change will override the default org template and removes some of the less relevant sections for AMIgo. The intention is to make the review processes for AMIgo PRs clearer and quicker.
Read the PR template, see if it is clearer how reviews should be conducted.
Recipe & role PRs get assigned a reviewer faster, and get merged faster consequently.
We could make it more confusing!

Adds a PR template

---

roles/kong-v1_5/files/kong-1.5.1.conf
roles/kong-v1_5/files/protect-admin-port/healthcheck-index.html
roles/kong-v1_5/files/protect-admin-port/nginx.conf
roles/kong-v1_5/files/protect-admin-port/protect-admin-port.service
roles/kong-v1_5/tasks/main.yml

Adds extra configuration to apply a secondary reverse-proxy for Kong's admin endpoint. The endpoint is still firewall protected in deployment (through the use of Security Groups); this is part of an infrastructure rationalisation and defence-in-depth measure agreed with Infosec.
In addition to the existing Security Group configuration which blocks the port to everything except known SGs, we are adding a basic auth challenge which will be set from Secrets Manager (and ultimately auto-rotated, we hope)
Once the instance is built, it will have an extra service called protect-admin-port and associated configuration. The Kong configuration is modified to shift the admin port to 8101, localhost only, and protect-admin-port sets up a simple authenticating nginx proxy to protect it.
The user …

Kong admin port protection

---

build.sbt
script/ci

https://github.com/guardian/amigo/pull/944 introduced Scalafmt. This PR fixes two related issues:
1) we did not check SBT files
2) more importantly, because the SBT projects were not [aggregated](https://www.scala-sbt.org/1.x/docs/offline/Multi-Project.html#Aggregation) Image Copier was not formatted or checked at CI time - so we fix this here
Note, the lack of aggregation means that Image Copier could be failing tests without CI telling us (presumably a long-standing issue). Aggregation fixes this too.

Scalafmt fixes

---

roles/teamcity-agent/tasks/main.yml

Establish a new domain name for TeamCity agent/server communication. See https://github.com/guardian/deploy-tools-platform/pull/663 for more background and reasoning.
- Bake the `teamcity-agent` recipe
- Following [these instructions](https://github.com/guardian/deploy-tools-platform/blob/b190a9a1df6b3e5032d41a6785eae51aecd156f5/docs/testing-teamcity-agent-amis.md) to test the baked AMI.

Set custom `serverUrl` on agent

---

roles/teamcity-agent/tasks/main.yml

It appears that regardless of the value of `serverUrl` in the agent's configuration, the agent will still phone home on the server's Server URL (https://www.jetbrains.com/help/teamcity/configuring-server-url.html).
This change does not meet our use-case described in https://github.com/guardian/deploy-tools-platform/pull/663, so reverting.
N/A - we're reverting back to a previous state, before #1003.

Revert setting of `serverUrl` on TeamCity agents

---

roles/teamcity-agent/tasks/main.yml

The changes in #1003 did not work (and were reverted in #1006); the agents were not using the updated URL.
It turns out TeamCity agents started via a Cloud Profile get their server URL via the [Cloud Profile](https://www.jetbrains.com/help/teamcity/agent-cloud-profile.html#Specifying+Profile+Settings), rather than [`buildAgent.properties`](https://www.jetbrains.com/help/teamcity/configure-agent-installation.html#General+Agent+Configuration).
1. Deploy to CODE.
2. Bake the `teamcity-agent` recipe.
3. Update the server URL in the Cloud Profile.
4. Following [these instructions](https://github.com/guardian/deploy-tools-platform/blob/ae5bd6aa921962576561ae6ffc5002a7ac470414/docs/testing-teamcity-agent-amis.md) to test the baked AMI.
5. SSM SSH onto the agent.
6. Observe the agent's logs, …

feat(teamcity-agent): Download build agent from machine accessible domain

---

roles/aws-inspector/README.md

- Updates the README for the `aws-inspector` role to include that it is not required for images based on Ubuntu 20

Add docs that `aws-inspector` is not required for Ubuntu 20

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

> **Note**
> Only to be merged once comms have been sent.
Remove the `public.amigo.gutools.co.uk` CNAME as we've reverted to `amigo.gutools.co.uk`.
The removed resources include (for CODE and PROD):
- The 301 redirect from `public.amigo.gutools.co.uk` to `amigo.gutools.co.uk`
- The TLS certificate for `public.amigo.gutools.co.uk`
- The CNAME for `public.amigo.gutools.co.uk`

Remove `public.amigo.gutools.co.uk`

---

riff-raff.yaml

Remove an explicit S3 bucket name to resolve the Riff-Raff warning:
> Explicit bucket name in riff-raff.yaml. Prefer to use bucketSsmLookup=true, removing private information from VCS.
<details>
<summary>Screenshot from Riff-Raff</summary>
</details>
Riff-Raff will now use the bucket that's stored in the SSM Parameter `/account/services/artifact.bucket`. I've confirmed the value of this Parameter is correct via:
```sh
aws ssm get-parameter \
--name /account/services/artifact.bucket \
--profile deployTools \
--region eu-west-1
```
Deploy it? The warning should not be seen.

fix: Resolve Riff-Raff warning

---

app/views/showRecipe.scala.html

Updates the link added in #383:
- Do not scope to `riff-raff.yaml` file, to cater for cases where this is [auto-generated](https://github.com/guardian/cdk/blob/d50157ceb5f89cfa1b25cbe09d6da5cbd1d58edf/src/experimental/riff-raff-yaml-file/README.md)
- Do not include archived repositories
N/A
More exhaustive search on GitHub.
N/A

fix: Update GitHub usage link

---

roles/cloud-watch-agent-logs/README.md
roles/cloud-watch-agent-logs/files/configure-logs
roles/cloud-watch-agent-logs/meta/main.yml
roles/cloud-watch-agent-logs/tasks/main.yml

The existing [`cloud-watch-logs`](https://github.com/guardian/amigo/tree/main/roles/cloud-watch-logs) role uses a deprecated cloudwatch agent. This involves running an aws python script restricted to older versions of python. It fails on ubuntu Jammy.
This PR adds a new `cloud-watch-agent-logs` role which uses the new "unified" cloudwatch agent. This uses the existing `aws-cloud-watch-agent` role, and just provides a shell script for configuring logging. This script takes the same params as the old `cloud-watch-logs` script.

cloud-watch-agent-logs

---

roles/cdk-base/meta/main.yml
roles/cdk-base/tasks/main.yml

This change conditionally installs the correct version of fluentbit for the underlying OS release.
Currently some of our focal (20.04) images are using the bionic (18.04) build of fluentbit, and this role does not at all on jammy (22.04) as the bionic build tries to use a version of libssl unavailable on jammy. 
Bake an AMI in AMIgo CODE that uses this new recipe with each underlying OS version (18,20,22). Use the new bake in the CODE environment for a service that uses this recipe and ensure that logs are still being shipped to logs.gutools.
Deployed: https://riffraff.gutools.co.uk/deployment/view/7b075c1a-83c8-4711-b281-442d14b0dad4
Testing in:
This change will put the correct version of fluentbit on our bionic based recipes, and hopefully unlock jammy builds that use the cdk-base role …

Vary the version of fluentbit installed with the OS version

---

riff-raff.yaml

Move to use https://amigo.gutools.co.uk/recipes/arm64-jammy-java11-deploy-infrastructure.
This will allow us to:
- Move AMIgo to 22.04 to extend the EOL even further than https://github.com/guardian/amigo/pull/1017
- Test whether the new `arm64-jammy-java11-deploy-infrastructure` image is working as expected, following https://github.com/guardian/amigo/pull/1066
Deploy this PR to the CODE environment and check the EC2 instances with the new AMI are successfully brought into service & that we can access the AMIgo UI.
See: [no deployment yet]
Can we use the jammy AMI to successfully deploy AMIgo?
AMIgo is not deployable with Jammy base AMIs, we'll revert.

Use arm64-jammy-java11-deploy-infrastructure as the AMI

---

roles/neo4j/defaults/main.yml
roles/neo4j/tasks/main.yml

Neo4j have moved from .org => .com; updating repo location accordingly.

Update neo4j repo location

---

app/housekeeping/utils/PackerEC2Client.scala
app/packer/PackerBuildConfigGenerator.scala

This change adds a "Name: Packer Builder" tag when launching packer EC2 instances.
Deployed in CODE this should tag instances as expected and terminate any EC2 instances with the appropriate tags that have not been stopped in the last hour.
See: https://riffraff.gutools.co.uk/deployment/view/2144a848-363d-4d49-9799-6b4770e4ffe7
In CODE new instances are properly tagged:
The `DeleteLongRunningEC2Instances` housekeeping task which should terminate packer instances that have failed to be properly terminated is not working as the `Name` tag has not been added. 
This is because the aws packer plugin [no longer adds the Name tag itself](https://github.com/hashicorp/packer-plugin-amazon/blob/5d4e6b1680d345dfa0bf66f84a39e61057b3b098/docs-partials/builder/common/AMIConfig-not-required.mdx?plain=1#L …

Add "Name: Packer Builder" tag when launching packer instances

---

roles/filebeat/tasks/main.yml

This change adds a task to the filebeat role to install the ARM version of filebeat if architecture is aarch64. It also adds a condition to the existing task, so that builds only install their respective versions. 
Cost reduction benefits around AWS graviton instances.
Behavior of role has been preserved, so this shouldn't impact existing uses.

Make filebeat role support ARM

---

roles/teamcity-agent/tasks/main.yml

On 23 March 2023, [GitHub updated their key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/). In this change we update the signature (added in #391) to ensure we don't see warnings. The new value is taken from [official documentation on GitHub’s SSH public key fingerprints](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints).
It's tricky. In theory, we should also be seeing [the warning message](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/#what-you-can-do) on builds, with the agents failing to verify the host key. However, I've run a few builds this morning, and cannot see evidence of this. Maybe there's some propagation happening still?
We _could_ perform the same [test in …

fix: Update GitHub SSH-RSA key fingerprint

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

Increase the size of the EC2 instance used by Amigo from T4G.SMALL to T4G.XLARGE.
Background:
EC2 instances have been crashing with regularity. It looks like these crashes correspond to scheduled bakes.
While AWS does not provide any out-of-the box memory tracking metrics, it does seem likely from the logs that the EC2 instance is stalling due to lack of memory.
By increasing the size of the Amigo instance to a very large size instance, we can eliminate the possibility of memory issues occurring. 
If we run this larger size for a week, and no crashes occur, we know the problem is resource availability. We can then look at trying smaller sizes until we get the smallest size that remains stable.
This is a test.
To check this change has taken effect, after deployment of this build, get the …

Confirm the crashes of Amigo instances are due to resource issues by testing a larger instance - increase the instance to T4G.XLARGE

---

roles/cdk-base/README.md

`cdk-base` has been adopted by a [significant number of recipes ](https://amigo.gutools.co.uk/roles#cdk-base) and we are now [recommending/supporting](https://github.com/guardian/recommendations/pull/118) it as a stable method for shipping logs. Consequently this PR updates some documentation that was added whilst this tooling was still being developed.

Update cdk-base documentation

---

build.sbt
project/build.properties

Manually bumps various dependencies whilst our Scala Steward integration appears to be a little broken. Hoping this'll reduce the noise created by https://github.com/guardian/actions-prnouncer 🤞🏽.
| Module      | From      | To        |
|-------------|-----------|-----------|
| Jackson     | 2.15.0    | 2.15.1    |
| AWS SDK v1  | 1.12.458  | 1.12.473  |
| AWS SDK v2  | 2.20.56   | 2.20.69   |
| Scanamo     | 1.0.0-M24 | 1.0.0-M26 |
| scalatest-* | 3.2.15    | 3.2.16    |
| sbt | 1.8.2    | 1.8.3    |
- [Deploy to CODE](https://riffraff.gutools.co.uk/deployment/view/9b4a5a51-7758-44cb-a428-7d738505bc1b)
- Can an AMI be baked? ([spoiler: yes it can!](https://amigo.code.dev-gutools.co.uk/recipes/akash-test/bakes/6))
---
Closes #1164.
Closes #1167.
Closes #1168.
Closes #1169.
Closes #1171. …

chore(deps): Bump various dependencies

---

app/housekeeping/TimeOutLongRunningBakes.scala

This PR makes AMIgo's housekeeping (which tidies up bakes that are presumed to be stuck) a little more patient. Currently it marks bakes as `TimedOut` after ~1 hour, but we have at least one [recipe](https://amigo.gutools.co.uk/recipes/ubuntu-jammy-datascience-python-ner-cuda) which regularly takes longer than this to bake.
We are just changing a timeout value here, so I haven't done any testing.
After this change is merged we should stop sending spam alerts to @michel-ds. 
The feedback loop for bakes which are 'stuck' will be longer. As most bakes run overnight I don't think this is a particularly problematic risk. This will also cost us a bit of extra money, but the hourly pricing for [the EC2 instances that we're using](https://github.com/guardian/amigo/blob/b44d6db5fca946e4306000e6a4b0 …

Allow bakes to run for longer before marking them as TimedOut

---

app/components/AppComponents.scala
app/data/DynamoFormats.scala
app/event/BakeEvent.scala
app/models/BakeStatus.scala
app/models/CustomisedRole.scala
app/models/packer/PackerBuildConfig.scala
app/models/packer/PackerProvisionerConfig.scala
app/models/packer/PackerVariablesConfig.scala
app/prism/RecipeUsage.scala
build.sbt
test/prism/PrismSpec.scala

Reverts guardian/amigo#1191 as it's causing some NPE to be thrown, and a [deployment failure](https://riffraff.gutools.co.uk/deployment/view/f3333c2c-0292-41e5-8937-964781311b53?verbose=true). As observed in the cloud-init logs:
```log
Failed to start application due to java.lang.NullPointerException
```

Revert "Non-AWS dependency updates"

---

.github/dependabot.yml

Corrects the configuration added in #1203 - the ignore rules should be in the NPM `package-ecosystem`.
See https://github.com/guardian/cdk-playground/blob/main/.github/dependabot.yml as a comparison.

chore(deps): Correct Dependabot configuration

---

app/components/AppComponents.scala
app/data/DynamoFormats.scala
app/event/BakeEvent.scala
app/models/BakeStatus.scala
app/models/CustomisedRole.scala
app/models/packer/PackerBuildConfig.scala
app/models/packer/PackerProvisionerConfig.scala
app/models/packer/PackerVariablesConfig.scala
app/prism/RecipeUsage.scala
build.sbt
test/prism/PrismSpec.scala

Reverts guardian/amigo#1212 as there is some kind of Scanamo bug which has surfaced with these updates:

Revert "Scala Steward weekly dependency updates"

---

app/components/AppComponents.scala
app/controllers/BakeController.scala
app/event/Behaviours.scala
app/event/EventBus.scala
app/services/PrismData.scala
build.sbt

~~*UPDATE: the build is now failing as Pekko have pulled the release-candidate 1 that was published. We're at the cutting edge folks! See https://lists.apache.org/thread/0jl8qm0owv7r81v89pnc0o00ys9d6x37. They plan to redo the release in a couple of days so will bump then. On the positive side, the test to CODE worked! I was able to successfully bake an image, and the housekeeping jobs were running.*~~ Pekko have now release a v1. 🎉 
Migrates from Akka to [Pekko](https://pekko.apache.org/). This is a test to better understand the process and evaluate Pekko's readiness.
Deploy to CODE and build some things. Also check the logs for any errors.
Akka have introduced licensing changes and we therefore want to migate away from it by Sept 2023. The clearest migration path is to use Pekko instead. …

Migrate from Akka to Pekko

---

.scala-steward.conf

Hopefully fixes the Scala Steward definition. Good error reporting from SS helps here:

Fix frequency definition - requires @ prefix

---

.github/dependabot.yml
.scala-steward.conf

This PR reconfigures our dependency management configuration using this script:
https://github.com/guardian/configure-dependency-management
The previous approach attempted to use the `combine-prs` action to consolidate individual PRs from Dependabot and Scala Steward. The benefit to this was (in theory):
* a single grouped PR, which is easier to review/manage
* while running updates against individual PRs first to isolate any CI errors
Unfortunately, the approach has some issues:
1. combine-prs doesn't have any way to close the individual PRs, leaving a lot of manual work (see: https://github.com/github/combine-prs/issues/25)
2. Scala Steward combines the central configuration with our own, which means grouping is always applied anyway
Another issue is that individual PRs need to be …

feat: add Dependabot config

---

.github/dependabot.yml

(A test of @guardian/automerge.)
* stop batching Dependabot PRs
* schedule Dependabot to ensure it runs during our working hours
Following this change, and once we have manually added the automerge Github App to this repo, we should see bot-raised PRs automatically merged in provided status checks pass.
Obviously this adds some risk but CI passing should give us confidence here. And PRs are only merged in during weekdays and between 9-5.
@see https://github.com/guardian/automerge

Configure Dependabot for @guardian/automerge

---

roles/cdk-base/README.md

When working on https://github.com/guardian/editorial-tools-platform/pull/703 / https://github.com/guardian/targeting/pull/183 nothing was shipping to ELK and we noticed the following in td-agent-bit's own log output... 
...turns out we were missing `kinesis:PutRecords` in our IAM policy.
This PR corrects the documentation to cover all required IAM actions.

docs(cdk-base): fix missing IAM action kinesis:PutRecords

---

roles/cloud-watch-monitoring/tasks/main.yml
roles/usage-monitoring-agent/files/monitoring.sh

This changes is motivated by Editorial tools bakes failing because HTTP endpoints now return 403 for this resource.
But HTTPS is A Good Thing, so we probably should have been doing this anyway.
I haven't seen any notification from AWS of this change.
Minor change, testing almost not required.  But triggering a bake of any of the recently failed ed tools recipes should verify the fix.

Use HTTPS S3 urls to download CloudWatchMonitoring scripts

---

app/notification/BakeFailedNotifier.scala

As part of the response to the incident, AMIgo is now available without the VPN.

Remove VPN required hint from failed bake notification

---

roles/docker/README.md

This adds a little extra detail in the README about what to pass into the docker version parameter when using docker as a role, to hopefully prevent other people from messing with it for as long as I've done...

add formatting detail to docker role readme

---

roles/whisper-cpp/tasks/main.yml

Removes the download of large whisper model from whisper role so that we only download base, small, medium
We've decided not to use this model for the moment. This should help us avoid bakes timing out.

Remove download of large whisper model from whisper role

---

roles/whisper-cpp/defaults/main.yml
roles/whisper-cpp/tasks/main.yml

Our whisper.cpp build timed out. This PR aims to help the situation by:
- removing the 'large' model (over 3 GB) - it's unlikely we'll be able to use this model in production any time soon
- not throwing away the output from the downloads (so we can see where they fail)
In addition, given that new features to whisper.cpp are being added a lot faster than they are doing releases, I've changed our checkout behaviour so that we fetch the whole repo then reset to  a specific commit ID. This way we can either pin to a certain release or jump to the latest if we see something promising in recent changes to whisper.cpp 
This needs a quick test on amigo CODE prior to merging

Whisper.cpp: remove large model, parameterise git commit id to work from

---

roles/java21corretto/README.md
roles/java21corretto/meta/main.yml
roles/java21corretto/spec/java21corretto_spec.rb
roles/java21corretto/tasks/main.yml

Adds a new Amigo role because of one the dependencies that we use in our project requires JRE 21, which is the latest  long-term support release.
Note that this will be used for a CODE-only service - in production we'll be running the application in a container using the [`amazoncorretto:21`](https://hub.docker.com/_/amazoncorretto/) image.

Add `java21corretto` role

---

roles/java21corretto/tasks/main.yml

Fixes a typo in the `java.security` path
I accidentally missed a `-`, so the bake is failing with this message:
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Path /usr/lib/jvm/java21-amazon-corretto/conf/security/java.security does not exist !", "rc": 257}
```
Deployed to CODE Amigo and the installation succeeded. Note how the step didn't fail:
```
changed: [127.0.0.1] => {"backup_file": "/usr/lib/jvm/java-21-amazon-corretto/conf/security/java.security.39338.2023-12-11@18:31:25~", "changed": true, "msg": "1 replacements made"}
```

fix: Fix `java.security` path in `java21corretto` role

---

roles/whisper-cpp/README.md
roles/whisper-cpp/defaults/main.yml
roles/whisper-cpp/tasks/main.yml

We're doing a lot of experimentation with different whisper models at the moment and having to modify the role every time is getting a bit tedious. This change parameterises the names of the models which are downloaded when baking an AMI with the whisper role.
There's a bake currently in progress [here](https://amigo.code.dev-gutools.co.uk/recipes/investigations-ocrmypdf/bakes/13) - let's see if it works....

(whisper cpp role) Use parameter to determine which whisper models are downloaded

---

app/components/AppComponents.scala
build.sbt

Updates all of our dependencies to versions that use Play 3. Right now we have both Akka and Pekko in our dependency tree which isn't ideal.
Before:
After:

Upgrade all dependencies to Play 3

---

roles/docker/tasks/main.yml

On linux some extra steps have to be taken after installing docker so that it can be run by a non-root user. These are documented here https://docs.docker.com/engine/install/linux-postinstall/
Our role already did the thing of creating the docker group (step 1 of above docs) but didn't add the ubuntu user to that group (step 2). This PR resolves that. 
Tested in this build https://amigo.code.dev-gutools.co.uk/recipes/investigations-ocrmypdf/bakes/30
Output:
```
[2024-02-07 12:09:02] investigations-ocrmypdf: TASK [docker : Add ubuntu user to docker group] ********************************
[2024-02-07 12:09:03] investigations-ocrmypdf: changed: [127.0.0.1] => {"append": true, "changed": true, "comment": "Ubuntu", "group": 1000, "groups": "docker", "home": "/home/ubuntu", "move_home": false, …
```

Apply docker postinstall steps when installing dockerAdd ubuntu user to docker user group

---

roles/browser-testing/meta/main.yml

Removes the dependency from the role itself, enabling us to specify the java version in the AMI recipe through one of the associated roles instead.
This role is used in a recipe for the production monitoring tool, which uses chromedriver for automated browser testing. For context, we are in the process of updating [prodmon to play 3,](https://github.com/guardian/editorial-tools-production-monitoring/pull/331) which has required an update to java 11. 
Once we've updated the existing recipe to use java 8 and created one for java 11, we'll need to try to deploy the updated branch of prodmon to verify this is all working as intended. 
The next scheduled bakes for the recipes which use this role are next Tuesday, giving ample time to respond to any issues.

Remove java8 dependency from browser testing role

---

roles/aws-efs/meta/main.yml
roles/aws-efs/tasks/main.yml

efs utils now has a [dependency on rust](https://github.com/aws/efs-utils?tab=readme-ov-file#on-other-linux-distributions), and various other libraries which are added as part of this change
Tested on Amigo CODE  here https://amigo.code.dev-gutools.co.uk/recipes/investigations-ocrmypdf

Add required dependencies for aws-efs

---

roles/aws-rds-root-cert-ca/tasks/main.yml
roles/aws-rds-root-cert-ca/vars/main.yml

This PR updates the aws_rds_root_cert_ca to support new rds certificates which come in bundles instead of single files.
Looking at the [documentation on using ssl in RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html) it looks like now instead of a single certificate there's bundles. The current code assumes the file that it gets from AWS contains a single certificate so if we try to use the new urls it would only load the first one.
A good side effect of loading the certificate in bundles is that it includes the deprecated certificate as well so applications that use it would work with either, which makes migrating with minimal downtime easier.
For a first test we can sign in to an instance that uses this role and find the generated trust store file (by …

update aws_rds_root_cert_ca role to load new certificate bundle

---

roles/kong/defaults/main.yml
roles/kong/tasks/main.yml

As part of our `kong` [role](https://amigo.gutools.co.uk/roles#kong), we download the application [Kong](https://konghq.com/) from a known URL (this is an essential application that implements the API keys for CAPI).
However, a few months ago, this stopped working. A bit of digging revealed that the Kong team had changed the URL for the download.
I have updated the URL for the role, and I have tested that it now works by first running the role locally with `multipass` and then deploying this branch to code and [re-running the build](https://amigo.code.dev-gutools.co.uk/recipes/kong-v3-arm/bakes/2). I also confirmed in the former case that if I ssh onto the box I can see that kong is installed.
I have also [deployed](https://riffraff.gutools.co.uk/deployment/view/3171679b-7eae-4f84-85b3-dcb …

the url for downloading Kong has moved

---

roles/cdk-base/README.md
roles/cdk-base/defaults/main.yml
roles/cdk-base/tasks/main.yml

Adds an option to the cdk-base role to _not_ automatically start fluentbit on instance start
Create a recipe using this role with `start_fluentbit: false` in the custom variables. Does the instance automatically start sending logs, or does it wait for a command (either from a logged in dev or the user data script) to start?
Currently if you want or need to add extra fluentbit config at instance start time (ie. in user data script) you must `systemctl restart td-agent-bit.service`, which means that the cloud-init logs up to that point will be resent from the start, meaning some logs are sent twice! If instead we never add the start-fluentbit script, we can start it when we have the full config in place, and still benefit from `devx-logs`!
Is a user of this option has a user data script …

cdk-base: Add option to not automatically start fluentbit

---

app/prism/Prism.scala
app/prism/RecipeUsage.scala
app/services/PrismData.scala
app/views/fragments/usagesColumn.scala.html
app/views/showUsage.scala.html
test/housekeeping/MarkOldUnusedBakesForDeletionSpec.scala
test/prism/RecipeUsageSpec.scala

We encountered an issue recently where AMIgo was reporting a recipe as unused, when it actually was in use but via a [launch template](https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-templates.html) rather than a [launch configuration](https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-configurations.html).
This PR should prevent that from happening again by adding launch template support to AMIgo - so that when it checks whether a bake is in use, it will also check for usages within launch templates.
I tested this on AMIgo CODE against Prism CODE (with this branch https://github.com/guardian/prism/pull/918) by adding an AMIgo CODE AMI to a launch template and checking that the usage is picked up by AMIgo

Add launch template support to AMIgo

---

roles/aws-tools/tasks/install-pip-aws-cli-Debian.yml
roles/aws-tools/tasks/install-pip-aws-cli-RedHat.yml
roles/aws-tools/tasks/main.yml

PR #66 updated the `aws-tools` role to work with RedHat. This was to enable the `s3-ssh-keys` on this distribution.
The `s3-ssh-keys` role has subsequently been removed (#388). Thus, we can simplify the `aws-tools` role by removing RedHat support.
- [Deploy to CODE](https://riffraff.gutools.co.uk/deployment/view/1abe54f0-dcea-421b-9849-edb0478e9f22)
- [Bake an image and ensure the AWS CLI is still available](https://amigo.code.dev-gutools.co.uk/recipes/arm64-jammy-java11-deploy-infrastructure/bakes/12)
Fewer code branches.
N/A - as noted above, the purpose for adding RedHat support has been removed.
> **Note**
> If this change adds, updates or removes a role or recipe please note that in your PR and assign appropriate reviewers for the team that will be impacted by those changes.

feat(aws-tools)!: Remove support for RedHat

---

roles/friendly-hostnames/README.md
roles/friendly-hostnames/defaults/main.yml
roles/friendly-hostnames/files/hostnames.txt
roles/friendly-hostnames/tasks/main.yml

This PR is intended to remove a direct dependency between the `friendly-hostnames` role and the Ophan Dist S3 bucket, which is currently required to be public for this to work. 
The change takes the resource from the Ophan Dist bucket and provides it directly as a resource in the role. 
[Relates to GChat Thread.](https://chat.google.com/room/AAAAwc4LMKU/Cs6jpX_Iu3s/Cs6jpX_Iu3s?cls=10)
I will test this on CODE to confirm it works as expected. 
[Test bake here.](https://amigo.code.dev-gutools.co.uk/recipes/elasticsearch-7-arm-test/bakes/1)
This changes will allow us to remove the S3 dependency of the `friendly-hostnames` role and set the bucket to private. 
Worst case scenario, this could cause issues for our ElasticSearch clusters, namely CAPI and Ophan, the consumers of this role.

Removes the Ophan Dist S3 bucket dependency from the friendly hostnames role

---

roles/aws-cloud-watch-agent/README.md
roles/cloudwatch-hardware-monitoring-cronjob/README.md

The `cloudwatch-hardware-monitoring-cronjob` role is not compatible with IMDSv2 and therefore violates [FSBP EC2.8](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-8). This change marks the role as deprecated and points to using `aws-cloud-watch-agent` instead.
The docs for `aws-cloud-watch-agent` is updated too to provide an example configuration file for ease. The configuration was taken from https://github.com/guardian/deploy-tools-platform/pull/843.
The ultimate test is to migrate from `cloudwatch-hardware-monitoring-cronjob` to `aws-cloud-watch-agent` and to comment on the helpfulness of the documentation.
A clearer path for teams to resolve FSBP EC2.8 issues in their services.
N/A.

docs: Mark `cloudwatch-hardware-monitoring-cronjob` role as deprecated

---

.tool-versions
build.sbt
imageCopier/src/main/scala/com/gu/imageCopier/AmiActions.scala
imageCopier/src/main/scala/com/gu/imageCopier/LambdaEntrypoint.scala
riff-raff.yaml

- Upgrade to `Java `21` using [amigo recipe](https://amigo.gutools.co.uk/recipes/arm64-jammy-java21-deploy-infrastructure) — 37d9f44
- Upgrade copier lambda to AWS SDK v2 — [1f80e21](https://github.com/guardian/amigo/commit/1f80e21647d3a3cfd4f2b85073242accf8c3c26a)

Update ImageCopier to  Aws SDK v2 

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/image-copier-lambda.test.ts.snap
cdk/lib/image-copier-lambda.test.ts
imageCopier/README.md

- Updates the version of the image copier lambda 
- Updates the README to reflect the steps required to rename the artifact
Once the stackset has been redeployed, we should see a reduction vulnerabilities reported by Inspector for this lambda.
To ensure that the latest version with the latest dependencies is deployed when we redeploy the stackset.

feat: update image copier lambda

---

app/controllers/BaseImageController.scala
app/data/BaseImages.scala
app/models/BaseImage.scala
app/packer/PackerBuildConfigGenerator.scala
app/packer/PackerRunner.scala
app/views/editBaseImage.scala.html
app/views/newBaseImage.scala.html
app/views/showBaseImage.scala.html

I've been trying to build an AMI for https://github.com/m-bain/whisperX that includes all required Nvidia drivers. I've got this working by using the AWS Deep Learning Base AMI (https://aws.amazon.com/releasenotes/aws-deep-learning-base-gpu-ami-ubuntu-22-04/) along with a custom AMIgo role that installs the various python dependencies. 
However, the base AMI requires at least 70GB of disk, and the whisperx dependencies are also enormous. Using the standard AMIgo t3.small instance type results in the bake failing due to pip running out of memory whilst installing the various python dependencies. Bumping to a .large instance solves that, but the bake then times out whilst trying to snapshot (something a bit like this https://github.com/hashicorp/packer/issues/7719). Using a .xlarge instance …

Add 'requiresXLargeBuilder' field to base image

---

app/packer/PackerBuildConfigGenerator.scala
roles/whisperx/meta/main.yml
roles/whisperx/tasks/main.yml

Depends on https://github.com/guardian/amigo/pull/1604
WhisperX is a transcription tool - see github repo here https://github.com/m-bain/whisperX. It is potentially a lot faster than the tool we currently use for transcription, and supports speaker identification which is a feature often requested by our users. 
This PR adds a role to AMIgo to install whisperx and associated dependencies. 
Tested on CODE - I baked an AMI and then booted an instance with it and verified that whisperx worked

Add WhisperX Role

---

roles/kong/tasks/main.yml

`postgresql-16` is not included in the apt repositories available in `[ubuntu-jammy (22.04 LTS)](https://amigo.gutools.co.uk/base-images/ubuntu-jammy%20(22.04%20LTS))`. This PR updates apt with the postgres repository as an initial step, to ensure `postgresql-16` is available.
Run the bake locally with `multipass` per the README. It should succeed. Tested locally:
postgres 16 available for Kong.
The image will be well tested before being deployed to PROD services. A failed or incorrectly configured bake is low risk.

Add step to configure postgres apt repository to enable installation of postgresql 16

---

roles/kong/defaults/main.yml
roles/kong/tasks/main.yml

Corrects the URL from which we fetch Kong, with an additional parameter for the Ubuntu release — we're now on Jammy.
Also adds the missing configuration file for 3.9.0.
The bake should succeed with the appropriate parameters bumped for 3.9.0:
```
---
kong_version: 3.9.0
kong_user: content-api
postgres_version: 16
kong_arch: arm64
kong_ubuntu_release: jammy
kong_repo: gateway-39
```
Tested locally 👍

Correct Kong URL with additional parameter for Ubuntu release

---

roles/kong/tasks/main.yml

Corrects an incorrect task property in the `kong` recipe. Tested locally with multipass:
Run multipass locally to test the role. It should run without errors.

Correct task property

---

app/prism/RecipeUsage.scala
test/prism/RecipeUsageSpec.scala

Launch template support was added last year, but it doesn't look like the UI was fully updated to reflect this. This means a manual tidy up job might accidentally remove recipes that appear to be unused despite being referred to by launch templates.
We add this check to the logic, so that the "Unused recipes" section of the recipes index is correctly populated. This also improves the usage checks on base images page.
This adds a couple more tests for the `hasUsage` function, to cover non-instance usages explicitly.
This should help prevent manual clear-ups from removing recipes that are still in use.
> **Note**
> If this change adds, updates or removes a role or recipe please note that in your PR and assign appropriate reviewers for the team that will be impacted by those changes.

The recipe `hasUsage` function now includes launch template checks

---

README.md
multipass/clean.sh
multipass/run.sh

Multipass has changed a bit since these scripts were originally written. I've updated the scripts and made some tweaks that made my life easier when getting this to run locally.
Running `./multipass/run.sh` should work correctly up to the point it tries to execute an ansible role (the default one set in playbook.yml uses an artificial name to make it fail fast)

Tweaks to multipass scripts

---

cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

Builds on https://github.com/guardian/amigo/pull/1652.
Removes the unused `WazuhSecurityGroup` security group. This is the second and last stage of updating to GuCDK v61.5.0. See https://github.com/guardian/cdk/releases/tag/v61.5.0.
See the updated snapshot.
Successfully [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/b51571a4-4d04-4450-a7f7-78bbecc8906e).

feat(cdk): Remove the `WazuhSecurityGroup` security group

---

app/packer/PackerRunner.scala
cdk/lib/__snapshots__/amigo.test.ts.snap
cdk/lib/amigo.ts

Relates to https://github.com/guardian/amigo/pull/1661.
Update to the latest version of Packer.
1. Deploy this branch to CODE
2. Confirm this branch is running on CODE by checking the build number on https://amigo.code.dev-gutools.co.uk/healthcheck
3. Bake a recipe
4. Launch an instance using the AMI produced from step 3
I've [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/8a8a3715-b127-496c-af3f-c68e72948c0d) and [successfully baked an image](https://amigo.code.dev-gutools.co.uk/recipes/arm64-jammy-java11-deploy-infrastructure/bakes/41) and used it on https://github.com/guardian/cdk-playground/pull/752.
Keeping up to date.
From the [CHANGELOG](https://github.com/hashicorp/packer/blob/main/CHANGELOG.md) the only breaking change that impacts AMIgo is a change to how …

feat: Update Packer from 1.8.5 to 1.13.1
